<Project>
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <LangVersion>14</LangVersion>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <Configurations>Debug;Release;Release-R2R;Debug-Windows;Debug-NoZFS</Configurations>
    <Platforms>x64</Platforms>
    <DebugType>embedded</DebugType>
    <CheckForOverflowUnderflow>True</CheckForOverflowUnderflow>
    <RuntimeIdentifiers>linux-x64;win-x64</RuntimeIdentifiers>
    <AnalysisLevel>10-recommended</AnalysisLevel>
  </PropertyGroup>
  <PropertyGroup>
    <VersionPrefix>3.0.0</VersionPrefix>
    <VersionSuffix>alpha1</VersionSuffix>
  </PropertyGroup>
  <PropertyGroup>
    <Copyright>2026 Brandon Thetford and the SnapsInAZfs Organization</Copyright>
    <Description>SnapsInAZfs - Snapshot manager for ZFS on Linux</Description>
    <Product>SnapsInAZfs</Product>
  </PropertyGroup>
  <PropertyGroup>
    <NoWarn>NU1510</NoWarn>
  </PropertyGroup>
  
  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Configuration" Version="10.0.8" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" Version="10.0.8" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Binder" Version="10.0.8" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="10.0.8" />
    <PackageReference Include="Microsoft.Extensions.Options" Version="10.0.8" />
    <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" Version="10.0.8" />
    <PackageReference Include="JetBrains.Annotations" Version="2025.2.4" />
    <PackageReference Include="NLog" Version="6.1.3" />
    <PackageReference Include="NLog.Extensions.Logging" Version="6.1.3" />
  </ItemGroup>
  <ItemGroup>
    <Using Include="NLog" />
    <Using Include="System.Runtime.CompilerServices" />
  </ItemGroup>
  <Import Project="$(MSBuildThisFileDirectory)SystemSpecific.Build.props" />
  <PropertyGroup>
    <_SIAZ>$(Product)</_SIAZ>
    <_SIAZLC>$(_SIAZ.ToLower())</_SIAZLC>
    <_InstallRoot Condition="'$(_InstallRoot)' == ''">$(_AddOnSoftwareDir)/$(_SIAZ)</_InstallRoot>
  </PropertyGroup>

</Project>
