<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFrameworks>net9.0</TargetFrameworks>
		<DefineConstants>$(DefineConstants)</DefineConstants>
		<LangVersion>13</LangVersion>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<Configurations>Debug;Release;Release-R2R;Debug-Windows;Debug-NoZFS</Configurations>
		<Platforms>x64</Platforms>
		<DebugType>embedded</DebugType>
		<CheckForOverflowUnderflow>True</CheckForOverflowUnderflow>
		<RuntimeIdentifiers>linux-x64;win-x64</RuntimeIdentifiers>
    <RootNamespace>SnapsInAZfs</RootNamespace>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|x64'">
		<ContinuousIntegrationBuild>True</ContinuousIntegrationBuild>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release-R2R|x64'">
		<Optimize>True</Optimize>
		<GenerateDocumentationFile>False</GenerateDocumentationFile>
		<PublishReadyToRun>True</PublishReadyToRun>
		<PublishSingleFile>True</PublishSingleFile>
		<RuntimeIdentifiers>linux-x64</RuntimeIdentifiers>
		<TieredCompilation>False</TieredCompilation>
		<ContinuousIntegrationBuild>True</ContinuousIntegrationBuild>
	</PropertyGroup>
  
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|x64'">
    <DefineConstants>$(DefineConstants);JETBRAINS_ANNOTATIONS</DefineConstants>
  </PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug-Windows|x64'">
    <DefineConstants>$(DefineConstants);WINDOWS;JETBRAINS_ANNOTATIONS</DefineConstants>
		<RuntimeIdentifiers>win-x64</RuntimeIdentifiers>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="JetBrains.Annotations" Version="2025.2.0" />
		<PackageReference Include="NLog" Version="6.0.3" />
		<PackageReference Include="Polyfill" Version="[7.20.0,)" Condition="'$(TargetFramework)' == 'net8.0'">
		  <PrivateAssets>all</PrivateAssets>
		  <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
	</ItemGroup>
  
  <ItemGroup>
    <Using Include="System.Runtime.Versioning" />
    <Using Include="JetBrains.Annotations" />
    <Using Include="NLog" />
  </ItemGroup>

</Project>
