.ds SIAZB \fBSnapsInAZfs\fP
.ds SIAZ SnapsInAZfs
.ds SIAZLC snapsinazfs
.TH \*[SIAZB] 8 "July 15, 2023" "\*[SIAZB] Manual"
.SH NAME
.PP
\fB\*[SIAZB]\fP, \fB\*[SIAZLC]\fP, \fBsiaz\fP - Snapshot manager for ZFS
.PP
.SH SYNOPSIS
.PP
.SY \*[SIAZB]
.nh
.OP \-\-daemonize|\-\-no-daemonize
.OP \-\-debug|\-\-quiet|\-\-really-quiet|\-\-verbose|\-\-trace
.OP \-\-dry-run|\-\-dryrun
.OP \-\-no-prune-snapshots|\-\-prune-snapshots
.OP \-\-no-take-snapshots|\-\-take-snapshots
.hy
.PP
.SY \*[SIAZB]
.OP \fB\-\-check-zfs-properties\fP
.OP \-\-debug|\-\-quiet|\-\-really-quiet|\-\-verbose|\-\-trace
.PP
.SY \*[SIAZB]
.B \-\-prepare-zfs-properties
.OP \-\-dry-run|\-\-dryrun
.OP \-\-debug|\-\-quiet|\-\-really-quiet|\-\-verbose|\-\-trace
.PP
.SY \*[SIAZB]
.B \-\-config-console
.PP
.SY \*[SIAZB]
.B \-\-help|-h
.PP
.SY \*[SIAZB]
.B \-\-version
.YS
.PP
.SH DESCRIPTION
.PP
\*[SIAZB] is a snapshot manager for ZFS on Linux.\&
.PP
During installation, hard links are created so that \*[SIAZB] can be invoked as \fB\*[SIAZB]\fP, \fB\*[SIAZLC]\fP, or \fBsiaz\fP.\&
Documentation will refer to the application as \fB\*[SIAZB]\fP, but all three are synonyms, for invocation of the application.\&
.PP
\*[SIAZB] can be used to create snapshots on a schedule, on a per-dataset basis, with sub-hourly (\(dqfrequent\(dq), hourly, daily, weekly, monthly, and yearly periods, as well as destroy (\(dqprune\(dq) snapshots in each period, separately, based on the number of snapshots in that period, the total remaining space available, or a combination of both.\&
.PP
\*[SIAZB] can be run on-demand, at the command-line or via cron, or it can be run as a daemon (a systemd service unit is provided for that).\&
.PP
\*[SIAZB] also has a text interface configuration console, which can be invoked by starting \*[SIAZB] with the \fB\-\-config\-console\fP option.\&
.PP
General application configuration for \*[SIAZB] is in JSON-formatted text files.\&
.IP
See \fB\*[SIAZB](5)\fP for a complete description of these files.\&
.PP
Configuration that is relevant for interaction with ZFS,
such as enabling or disabling the taking or pruning of snapshots,
or retention settings for snapshot periods,
are stored in ZFS itself,
as user properties (see \fBzfsprops(7)\fP),
using the \(dq\*[SIAZLC].com:\(dq namespace.\&
.LP
These properties are metadata only and do not affect your ZFS filesystems,
nor do they create files on your system.\&
They also do not present a compatibility problem with any version of ZFS that \*[SIAZB] supports.\&
With the configuration console, manual user interaction with these properties is never necessary, in normal usage,
though you can modify them manually, at your own risk,
if you know what the resulting impact will be to the operation of \*[SIAZB].\&
If \*[SIAZB] does not understand the value of a manually\-modified property,
it will log an error or warning, as appropriate, and skip processing of that object and its children.\&
.IP
See \fBSnapsInAZfs-zfsprops(5)\fP for information on these properties.
.PP
.SH OPTIONS
.PP
\*[SIAZB] has several command-line options which may be optionally used when running it, to override the behavior configured in the JSON configuration files.\&
All options, except for
\fB\-\-help\fP,
\fB\-\-version\fP,
\fB\-\-config\-console\fP,
\fB\-\-prepare\-zfs\-properties\fP,
and \fB\-\-check\-zfs\-properties\fP,
have corresponding entries in configuration files,
and have final override authority over their corresponding configuration entries.\&
Many are provided as a convenience or for compatibility with sanoid, or are intended primarily for use in troubleshooting scenarios.\&
.PP
Some arguments that either make no sense together or are mutually exclusive are not allowed to be specified together on the command-line.\&
Such illegal combinations will be given in this document.\&
\*[SIAZB] will also explicitly reject invalid combinations of command\-line options and write the incompatibility error message to stdout.\&
.PP
\fBIn normal usage, you should not use command-line options.\fP\&
Instead, you should configure desired behavior in the configuration files and only use command-line options when you need to invoke \*[SIAZB] with different options for one\-off runs or troubleshooting.\&
.SS Informational options
.TP
\fB\-h\fP, \fB\-\-help\fP
.RS
.RS
Display brief usage information and exit.\&
.LP
This option cannot be combined with any other option.\&
.RE
.RE
.TP
\fB\-V\fP, \fB\-\-version\fP
.RS
.RS
Display version information and exit.\&
.LP
This option cannot be combined with any other option.\&
.RE
.RE
.SS Configuration Console
.TP
\fB\-\-config\-console\fP, \fB\-\-configconsole\fP
.RS
.RS
Launch the \*[SIAZB] configuration console utility,
to make changes to global JSON configuration, including general settings as well as templates,
or to make changes to configured properties in ZFS that control behavior of \*[SIAZB].\&
.LP
The configuration console is a TUI (text user interface), and should work inside most common terminal emulators.\&
\*[SIAZB] uses the
.UR https://github.com/gui\-cs/Terminal.Gui
Terminal.Gui
.UE
library for the TUI front\-end.\&
.LP
The configuration console will not make any changes to configuration without the user explicitly invoking the global save function,
or else without the application explicitly prompting the user about which zfs commands will be executed and requesting confirmation.\&
.LP
While the configuration console is displayed,
console logging will be temporarily disabled,
even if the user has attempted to explicitly configure alternative logging rules or targets in the nlog configuration to attempt to bypass this.\&
File logging, journald logging, or any other non-console logging options configured for nlog will continue to function as configured, while the configuration console is running.\&
.LP
Once the user exits the configuration console,
either by clicking on or selecting the Quit option in the File menu,
or by pressing the ctrl+q key combination on the keyboard,
\*[SIAZB] will terminate gracefully.\&
.LP
If an error occurs while using the ZFS Configuration Window of the configuration console that cannot be safely and deterministically recovered from,
which could leave the TUI in an inconsistent state,
the ZFS Configuration Window will close and will be disabled for the remainder of the current execution of \*[SIAZB],
to prevent creating a situation that could potentially have unexpected effects on configuration.\&
In general, however, this should only be possible if the user or some other process has manually modified the properties which \*[SIAZB] depends on,
which is a valid but unsupported use case,
since there are no safeguards against illegal values,
if modifications are made outside of \*[SIAZB].\&
.IP
See \fBSnapsInAZfs\-config\-console(8)\fP for complete documentation on the configuration console.\&
.IP
This option cannot be combined with: \fB\-\-Check\-zfs\-properties\fP, \fB\-\-dry\-run\fP, \fB\-\-prepare\-zfs\-properties\fP, \fB\-\-prune\-snapshots\fP, \fB\-\-take\-snapshots\fP
.RE
.RE
.SS ZFS property schema options
.TP
\fB\-\-check\-zfs\-properties\fP
.RS
.RS
Check \*[SIAZB] property schema in ZFS.\&
.LP
This causes \*[SIAZB] to check all pool root filesystems for expected properties that must be defined for \*[SIAZB] to take and prune snapshots,
and performs minimal validation/sanity checks on values,
and then exits without performing any further actions.\&
.LP
Missing or incorrect properties will be reported via nlog, at WARN level.\&
.LP
If no missing properties are found, with this argument specified, nlog logs that fact at INFO level.\&
.LP
Exit status will indicate the general result of the check.\&
See EXIT STATUS for details.\&
.IP
This option cannot be combined with: \fB\-\-config\-console\fP, \fB\-\-daemonize\fP, \fB\-\-prepare\-zfs\-properties\fP
.RE
.RE
.TP
\fB\-\-prepare\-zfs\-properties\fP
.RS
.RS
Check and update ZFS user properties for \*[SIAZB].\&
.LP
This causes \*[SIAZB] to check all pool root filesystems for expected ZFS user properties that must be defined for \*[SIAZB] to take and prune snapshots,
and then creates any that are missing.\&
.LP
Missing properties are created with default values and are defined explicitly on each pool root filesystem,
and are, in turn, inherited by all children of those filesystems.\&
.IP
This option cannot be combined with: \fB\-\-check\-zfs\-properties\fP, \fB\-\-config\-console\fP, \fB\-\-daemonize\fP
.RE
.RE
.SS Behavior-altering options
.TP
\fB\-\-daemonize\fP
.RS
.RS
Run \*[SIAZB] as a service.
.LP
This option corresponds to the global \(dqDaemonize\(dq setting in the JSON configuration files and has the same effect as setting that option to true.\&
.LP
This causes the program to stay running until a SIGINT or SIGTERM is received,
both of which will prompt \*[SIAZB] to cancel any pending actions and attempt a graceful shutdown.\&
SIGKILL is also accepted, but will force an immediate un-graceful stop of the process.\&
.LP
This option is intended for testing use and to support service managers such as systemd being able to force execution of \*[SIAZB] as a daemon,
even if the user has neglected to configure the JSON files appropriately for running as a daemon.\&
.LP
While this option can be manually specified when running \*[SIAZB] at the command-line,
it should be avoided in general usage, in favor of setting Daemonize to true in configuration.\&
.LP
Running under other service managers is likely possible, but is done at the user\(aqs own risk.\&
.IP
This option cannot be combined with: \fB\-\-no\-daemonize\fP, \fB\-\-check\-zfs\-properties\fP, \fB\-\-prepare\-zfs\-properties\fP, \fB\-\-config\-console\fP
.RE
.RE
.TP
\fB\-\-no-daemonize\fP
.RS
.RS
Opposite of \-\-daemonize \- Force \*[SIAZB] to run as normal
.LP
This option forces \*[SIAZB] to ignore the Daemonize setting in configuration files and explicitly sets it to false at run-time.\*
.LP
This will make \*[SIAZB] exit after one execution of the main program loop, like a normal invocation of the application, regardless of the Daemonize setting.\&
.LP
If you have set Daemonize to true in configuration files, using this option enables you to run the application manually, even while the service is active, without having to press ctrl+c to kill the process, once it is finished.
.LP
The primary use cases this was designed for are for making configuration changes using the configuration console,
using the \fB\-\-prepare\-zfs\-properties\fP option on a newly\-added pool,
forcing execution between scheduled periods,
or for troubleshooting with different options,
all without needing to stop the systemd service or change your running configuration.\&
.RE
.RE
.TP
\fB\-\-prune\-snapshots\fP
.RS
.RS
Prune snapshots, overriding the PruneSnapshots configuration option
.LP
This option causes \*[SIAZB] to prune existing eligible snapshots according to the
policy configuration specified in ZFS and associated templates.\&
.IP
This option cannot be combined with: \fB\-\-check\-zfs\-properties\fP, \fB\-\-config\-console\fP, \fB\-\-prepare\-zfs\-properties\fP
.RE
.RE
.TP
\fB\-\-no\-prune\-snapshots\fP
.RS
.RS
Opposite of \fB\-\-prune\-snapshots\fP - Do not prune any snapshots
.LP
This option will prevent \*[SIAZB] from pruning ANY snapshots, regardless of the PruneSnapshots setting in configuration files or the \*[SIAZLC].com:prunesnapshots property value set on any object in ZFS.\&
.LP
This option causes \*[SIAZB] to completely skip all code related to pruning snapshots, when running.\&
.IP
This option cannot be combined with: \fB\-\-check\-zfs\-properties\fP, \fB\-\-prepare\-zfs\-properties\fP, \fB\-\-prune\-snapshots\fP
.RE
.RE
.TP
\fB\-\-force\-prune\fP
.RS
.RS
No effect - provided for compatibility with sanoid only
.LP
This argument has no effect on the operation of \*[SIAZB], and is only provided for backward\-compatibility with sanoid, in case of scripted usage.\&
.LP
This option is obsolete in \*[SIAZB],
because \*[SIAZB] uses the deferred destroy operation,
when pruning snapshots,
which does not interfere with send or receive operations.\&
.IP
All users of \*[SIAZB] who are re\-using scripts previously used with sanoid are advised to remove this option from those scripts,
as it may be removed in a future version of \*[SIAZB].\&
.RE
.RE
.TP
\fB\-\-take\-snapshots\fP
.RS
.RS
Take snapshots, overriding the TakeSnapshots configuration option
.LP
This option will enable the code that takes snapshots, regardless of the TakeSnapshots setting in configuration files.\&
.LP
.BI NOTE: This does not override the \*[SIAZLC].com:takesnapshots property value set for any object in ZFS.\&
.LP
Causes SnapsInAZfs to take snapshots according to the policy configuration specified in ZFS and associated templates.\&
.IP
This option cannot be combined with: \fB\-\-check\-zfs\-properties\fP, \fB\-\-config\-console\fP, \fB\-\-no\-take\-snapshots\fP, \fB\-\-prepare\-zfs\-properties\fP
.RE
.RE
.TP
\fB\-\-no\-take\-snapshots\fP
.RS
.RS
Opposite of \fB\-\-prune-snapshots\fP - Do not create any new snapshots
.LP
This option will prevent \*[SIAZB] from creating ANY snapshots, regardless of the TakeSnapshots setting in configuration files or the \*[SIAZLC].com:takesnapshots property value set on any object in ZFS.\&
.LP
This option causes \*[SIAZB] to completely skip all code related to taking new snapshots, when running.\&
.IP
This option cannot be combined with \fB\-\-check\-zfs\-properties\fP, \fB\-\-prepare\-zfs\-properties\fP, \fB\-\-take\-snapshots\fP
.RE
.RE
.TP
\fB\-n\fP, \fB\-\-dryrun\fP, \fB\-\-dry\-run\fP, \fB\-\-readonly\fP, \fB\-\-read\-only\fP
.RS
.RS
Skip creation/deletion of snapshots (Simulate)
.LP
This option will make \*[SIAZB] perform a dry-run,
during which is will process all configuration items as normal,
but it will not actually execute any ZFS commands,
and, therefore, will neither create nor destroy snapshots,
nor will it set properties on existing objects, either.\&
.LP
At any point in the program where \*[SIAZB] \fIwould\fP have executed a ZFS command, it will instead output a log message at INFO level, beginning with the string \(dqDRY RUN:\(dq, and explaining the command that would have been invoked, had this option not been specified.
perform configured actions and report what it _would_ have done. No operations
that create or destroy ZFS snapshots will be performed, regardless of
configuration or other command-line options. If configuration or command line
options request to create or prune snapshots, this option will _simulate_
those actions without making changes to ZFS.
.IP
This option cannot be combined with: \fB\-\-config\-console\fP, \fB\-\-quiet\fP, \fB\-\-really\-quiet\fP
.IP
.SM Since this option is only useful for simulation, it cannot be combined with command\-line options that disable logging.\&
.RE
.RE
.SS Output and logging options
.TP
\fB\-q\fP, \fB\-\-quiet\fP
.RS
.RS
\(dqWARN\(dq level output logging
.LP
This option suppresses log messages for all configured rules that are less severe than WARN.\&
.LP
This option is intended for testing purposes (such as before setting the configured log level to WARN), and should not be used in general operation.\&
If you wish to log at a different level, configure the desired level on an appropriate rule in \*[SIAZB].nlog.json.\&
.RE
.RE
.TP
\fB\-qq\fP, \fB\-\-really-quiet\fP
.RS
.RS
No output logging
.LP
This option disables ALL logging output for all configured rules.\&
Use of this option is strongly advised against for any reason.\&
.LP
Change log level to \(dqOff\(dq in \*[SIAZB].nlog.json to set for normal usage.\&
.IP
Note: If nlog is configured for Trace logging in \*[SIAZB].nlog.json,
there may be logging output before this argument is parsed and activated.\&
.RE
.RE
\fB\-v\fP, \fB\-\-verbose\fP
.RS
.RS
\(dqINFO\(dq level output logging, with additional non-DEBUG output
.LP
This option is a logging pseudo-level between the default (INFO) level and DEBUG.\&
.LP
The minimum level logged with this option is still INFO,
except that some additional logging statements are enabled that are not logged without this option.\&
These log statements may provide information of interest to the user, but are not important enough to bother outputting for most use cases.\&
.LP
These additional log statements also do not have the severe negative performance implications that DEBUG or TRACE logging have, but are still wise to silence, if you do not explicitly need them.\&
.LP
These logging statements should also not be relied upon for monitoring purposes, as they are subject to change.\&
.RE
.RE
.TP
\fB\-vv\fP, \fB\-\-debug\fP
.RS
.RS
\(dqDEBUG\(dq level output logging
.LP
This option forces all cofigured logging rules that have their enabled property set to true to log at the DEBUG level.\&
.LP
This option is intended for troubleshooting purposes and should not be used in general operation.\&
If you wish to log at a different level, configure the desired level on an appropriate rule in \*[SIAZB].nlog.json.\&
.LP
Note that this level is very verbose and logs many operations that are not relevant outside of a troubleshooting or debugging context.\&
Console output, log files, or any other configured log targets may grow very large and may affect \*[SIAZB] and/or system performance,
especially for busy systems, systems with a large number of ZFS datasets and snapshots,
or for configurations that result in very frequent taking and pruning of large numbers of snapshots.\&
.RE
.RE
.TP
\fB\-vvv\fP, \fB\-\-trace\fP
.RS
.RS
\(dqTRACE\(dq level output logging
.LP
This option forces all cofnigured logging rules that have their enabled property set to true to log at the TRACE level.\&
.IP
.BI This is an extremely verbose logging level and has performance implications even when nothing is wrong.\&
.IP
.BI This option should ONLY be used in extreme troubleshooting or development/debugging situations.\&
.LP
A lot of the information logged is extremely uninteresting to most users, such as logging of internal operations that are not normally visible to the user.\&
You are almost guaranteed to have performance problems in \*[SIAZB] and potentially other applications, as well, if you use this options for normal operations.\&
.RE
.RE
.SH EXIT STATUS
.PP
0 Exit code indicates success
.PP
Non-zero exit codes indicate an error or some other condition that should
result in termination of or allow specific handling in scripts.\&
.TP
Specific exit codes:\&
.TQ
 \(bu 0: Normal exit status - Requested operations completed successfully or with no fatal errors.\&
.TQ
 \(bu 127: ECANCELED - Help or Version CLI argument was specified. Used to prevent inadvertent inclusion of those arguments in scripts.\&
.TQ
 \(bu 1079: EFTYPE - One or more JSON configuration files were missing or invalid.\&
.TQ
 \(bu 1093: ENOATTR - The ZFS property schema is not valid or an attempt to update the ZFS property schema failed.
.IP
Note that, though errno.c does define them and the value is a 32\-bit integner, exit codes greater than 255 are not understood by systemd and thus cannot be used for service control/restart conditions.\&
.SH ENVIRONMENT
.PP
.TP
$DOTNET_ROOT
.IP
This environment variable is only needed if you compile the application as a framework-dependent assembly.\&
There are no recipes provided in Makefile that perform such a compilation, so this is noted solely for informational purposes.
.TQ $PATH
.IP PATH must include the folder \*[SIAZB] was installed to.\&
By default, the \fBmake install\fP recipe installs the \*[SIAZB] executable and its hard-linked aliases to \fI/usr/local/sbin\fP.\&
\.\&
You can override the directory the binaries are placed in by setting \fI$LOCALSBINDIR\fP to the desired path,
when calling \fBmake install\fP, like so:
.nh
.B LOCALSBINDIR=\f(BI/install/path\fP make install\fR.\&
.hy
.SH FILES
.SS Binaries
.TP
/usr/local/sbin/\*[SIAZ]
.IP
The main program executable file.\&
.nh
This is also hard-linked to \f(BIsiaz\fP and \f(BI\*[SIAZLC]\fP, in the same directory.
.hy
.SS Configuration
.TP
.I /etc/\*[SIAZ]/\*[SIAZ].local.json
.IP
Local configuration file for \*[SIAZB].\&
.IP
This file is loaded after
.I /usr/local/share/\*[SIAZ]/\*[SIAZ].json\fR,
and overrides all matching items from that file.\&
Command-line options override settings in this and other configuration files.\&
.IP
.B This is the configuration file that is intended to be modified by the end-user.\&
.IP
See
.B \*[SIAZ](5)
for documentation of the configuration files.\&
.TP
.I /etc/\*[SIAZ]/\*[SIAZ].nlog.json
.IP
Local logging configuration file for \*[SIAZB].\&
.IP
This file is loaded after
.I /usr/local/share/\*[SIAZ]/\*[SIAZ].nlog.json\fR,
and overrides all matching items from that file.\&
Command-line options override settings in this and other configuration files.\&
.IP
.B This is the logging configuration file that is intended to be modified by the end-user.\&
.IP
\*[SIAZB] uses the nlog library for logging.\&
See
.UR https://nlog-project.org/config/
the nlog configuration documentation
.UE
for help modifying logging settings.\&
.TP
.I /usr/local/share/\*[SIAZ]/\*[SIAZ].json
.IP
The base configuration file for \*[SIAZB].\&
This file is loaded first, and any matching items are overridden by configuration in
.nh
.I /etc/\*[SIAZ]/\*[SIAZ].local.json
.hy
or command-line options.\&
.IP
.B This file is not intended to be modified by the end-user.\&
.IP
See
.B \*[SIAZ](5)
for documentation of the configuration files.\&
.TP
.I /etc/\*[SIAZ]/\*[SIAZ].nlog.json
.IP
The base logging configuration file for \*[SIAZB].\&
This file is loaded first, and any matching items are overridden by configuration in
.nh
.I /usr/local/share/\*[SIAZ]/\*[SIAZ].nlog.json\fR,
.hy
or command-line options.\&
.IP
.B This file is not intended to be modified by the end-user.\&
.IP
\*[SIAZB] uses the nlog library for logging.\&
See
.UR https://nlog-project.org/config/
the nlog configuration documentation
.UE
for help modifying logging settings.\&
.SS Service
.TP
.I /usr/lib/systemd/system/\*[SIAZLC].service
.IP
systemd service unit file for running \*[SIAZ] as a daemon under systemd.\&
.IP
This file contains the definition for the systemd service that can be installed using
.nh
.B make install-service\fR.\&
.hy
.IP
Installing the service via the \fBmake install-service\fP recipe will create or overwrite this file,
execute `systemctl daemon-reload`,
to refresh systemd\aqs configuration,
and then execute `systemctl enable snapsinazfs.service`,
which will make the service run at system boot, as well as create two aliases to the service:
.IR siaz.service and \*[SIAZ].service
, which can be used to interact with the service, unless it is disabled, at which point systemd will remove those aliases.\&
.IP
If you wish to make modifications to the service, you should do so by creating files with the `.conf` extension in
.I /etc/systemd/system/snapsinazfs.service.d/\fR.\&
(See \fBsystemd-unit(5)\fP)\&
.IP
Any configuration put in .conf files in that directory will be merged with the base service definition, by systemd.\&
Modifications you make to the original file in \fI/usr/lib/systemd/system/\fP are subject to being lost during future installs or upgrades of the application.\&
.IP
When run as a systemd service, \*[SIAZB] is executed with the \fB\-\-daemonize\fP option, by default.\&
.SS Log file directory
.TP
.I /var/log/\*[SIAZ]/
.IP
Log files for \*[SIAZ], by default, on a new installation, are written to this directory, in plain text.\&
Logging file location, format, and verbosity is highly configurable in \fI/etc/\*[SIAZ]/\*[SIAZ].nlog.json/fP.\*
.IP
\*[SIAZB] uses the nlog library for logging.\&
See
.UR https://nlog-project.org/config/
the nlog configuration documentation
.UE
for help modifying logging settings.\&
.SH EXAMPLES
.PP
These are potential common usage scenarios.\&
These scenarios assume your \fI\*[SIAZ].local.json\fP file has the
.BR TakeSnapshots and PruneSnapshots
options set to \fItrue\fR and \fBDryRun\fP set to \fIfalse\fP, unless otherwise noted.\&
.IP
\fBNote:\fP for \f(BIALL\fP invocations of \*[SIAZB],
including when \fB\-\-dry-run\fP or \fB\-\-config-console\fP are specified,
\*[SIAZB] will \f(BIALWAYS\fP check for existence of and very basic validity of the ZFS user properties it needs to operate.\&
If missing or invalid properties are detected on any pool roots,
\*[SIAZB] will terminate with an exit code and with log output indicating what's wrong,
to the best of its ability.\&
.IP
.B \*[SIAZ] does not currently support configurations having only some pools with \*[SIAZ] properties defined.\&
.TP
Normal execution
.IP
.B \*[SIAZ]
.IP
If invoked with no command line options,
\*[SIAZB] will first check for expected ZFS property schema on all pool roots,
and, if valid,
will first take snapshots,
and then prune snapshots,
as configured.\&
.TP
Simulation
.IP
.B \*[SIAZ] \-\-dry\-run
.IP
Runs \*[SIAZB] in simulation mode.\&
.IP
Useful for testing configuration changes without making any changes to ZFS.\&
Has the same effect as setting \fBDryRun\fP to \fItrue\fP in the JSON configuration files.\&
.IP
All other arguments behave as normal,
with the exception that, no matter which other arguments are specified,
no changes will be made to ZFS
(in other words,
no snapshots will be taken or pruned,
and no properties will be altered).\&
.
.
.TP
Backup/Replication
.IP
.B \*[SIAZ] \-\-no\-take\-snapshots
.IP
Skip taking new snapshots and only prune expired snapshots.\&
.IP
Useful on systems that receive snapshots from another system,
such as in a backup/replication setup,
where this system does not need to take new snapshots,
but should prune old snapshots.\&
.IP
While it is recommended that you do this via configuration,
rather than via command-line arguments,
this may provide a helpful guarantee that,
even if accidental changes are made or new datasets are received,
no new snapshots will be taken.\&
.IP
Also useful if you have just made a configuration change that would result in more snapshots being pruned,
and you wish to manually run \*[SIAZB] to observe the results,
possibly with a more verbose logging option or with \fB\-\-dry\-run\fP,
as well.\&
.TP
Viewing \*[SIAZ] \(dqconsole\(dq logs when running under systemd
.IP
systemd captures stdout from services and redirects it to the system journal, by default.\&
To view the journal entries from \*[SIAZ],
use the following commands, based on your systemd version:\&
.RS
.IP \(bu 2
version 245 or later
.RS
.IP
.B journalctl -x --namespace \*[SIAZLC]
.IP
For version 245 and up of systemd, journald has the concept of namespaces, to allow separation of logs from different applications.\&
The \*[SIAZB] service unit file is configured to make use of this feature.\&
On earlier versions of systemd, a warning will be logged by systemd when loading the service unit that it does not understand the namespace directive.\&
This can be safely ignored.\&
.IP
If you do not specify the namespace, you will not see journal entries from \*[SIAZB].\&
This is intentional, to keep it from cluttering up your system journal and to make troubleshooting easier.\&
.IP
If you make use of other services (not yet available) in the \*[SIAZ] family, they will also write to this namespace.\&
.RE
.IP \(bu 2
version 244 or lower
.RS
.IP
.B journalctl -x --unit \*[SIAZLC].service
.IP
For version 244 and lower of systemd, namespaces are not supported, so journal entries from \*[SIAZB] will be in the system journal.\&
.IP
This command filters the journal output to only include output produced by the \*[SIAZLC].service unit,
which is the same output that you would get from the newer version, but is stored intermixed with everything else in the system journal.\&
.RE
.RE
.SH AUTHORS
.PP
\*[SIAZ] is created by Brandon Thetford, and was inspired by sanoid\*(Tm, which was created by Jim Salter.\&
.SH REPORTING BUGS
.PP
The source code and issue tracker for \*[SIAZ] are hosted on GitHub, at
.UR https://github.com/snapsinazfs/snapsinazfs
.UE
.SH COPYRIGHT
.PP
Copyright 2023 Brandon Thetford
.PP
Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the “Software”), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
.PP
The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
.PP
THE SOFTWARE IS PROVIDED “AS IS”, WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
.SH SEE ALSO
.TP
.B \*[SIAZ](5)
.TQ
.B \*[SIAZ]\-zfsprops(5)
.TQ
.B \*[SIAZ]\-config\-console(8)
