.ds SIAZB \fBSnapsInAZfs\fP
.ds SIAZ SnapsInAZfs
.ds SIAZLC snapsinazfs
.ds SIAZNS \*[SIAZLC]\.com
.ds SCONF /usr/local/share/\*[SIAZ]/\*[SIAZ].json
.ds SLCONF /etc/\*[SIAZ]/\*[SIAZ].local.json
.ds SNCONF /etc/\*[SIAZ]/\*[SIAZ].nlog.json
.TH \*[SIAZB] 5 "July 17, 2023" "\*[SIAZB] Configuration Manual"
.SH NAME
.PP
\f(BI\*[SCONF]\fP , \f(BI\*[SLCONF]\fB  \- Configuration files for \*[SIAZ]\fP
.SH SYNOPSIS
.TP
\*[SCONF]
.TP
\*[SLCONF]
.TP
\*[SNCONF]
.TP
/usr/lib/systemd/system/\*[SIAZ].service (if service was installed, via \fBmake install\-service\fP)
.SH DESCRIPTION
.PP
These files contain the general operational parameters for \*[SIAZ], as well as the defintions of \fBtemplates\fP, which control naming and timing for snapshots (see \fBTEMPLATES\fP).\&
See \fB\*[SIAZ](8)\fP for general \*[SIAZB] documentation.\&
.SS CONFIGURATION PRECEDENCE
.PP
When \*[SIAZ] starts, it loads configuration in order, first from
\fI\*[SCONF]\fP, \fI\*[SLCONF]\fP, and then from \fI \*[SNCONF]\fP,
combining them into the final configuration, before any command-line options are used as final overrides of their corresponding settings.\&
Files of the same names,
but located in the same directory as the \*[SIAZ] executable will also be loaded,
by default, and in the same order.\&
.PP
Any configuration items defined in multiple files will be combined.\&
If the same key/value pair for any specific element exists in multiple files,
the value from files loaded later replaces the value loaded from previous files.\&
.PP
Configuration file loading can be overridden by the user,
by providing alternate configuration file paths in the \fB\-\-config\fP command\-line option.\&
See \fB\*[SIAZLC](8)\fP for details.\&
.IP
See
.B EXAMPLES
.SS FILE DESCRIPTIONS
.PP
.TP
\fI\*[SCONF]\fP
This is the default base configuration file for \*[SIAZ].\&
.IP
.B It is not intended to be modified by the user.\&
.IP
This file contains the default base settings that \*[SIAZ] needs to function, as well as the base definition of the \(dqdefault\(dq template.\&
.IP
If you wish to make a change to the default template,
use the configuration console
.nh
(\fB\*[SIAZ] \-\-config\-console\fP)
.hy
and save your changes to
.nh
\fI\*[SLCONF]\fP.\&
.hy
.TQ
\fI\*[SLCONF]\fP
This is the user\-editable configuration file for \*[SIAZ].\&
.IP
This file has the same schema as \fI\*[SCONF]\fP, and contains a sample template named \(dqproduction\(dq.\*
.IP
The recommended way to make changes to this file is to use the configuration console
.nh
(\fB\*[SIAZ] \-\-config\-console\fP)
.hy
and save your changes to
.nh
\fI\*[SLCONF]\fP.\&
.hy
.IP
Settings in this file extend and override settings in \fI\*[SCONF]\fP.\&
.TQ
\fI\*[SNCONF]\fP
This is the logging configuration file for \*[SIAZ].\&
.IP
\*[SIAZ] uses the
.UR https://nlog-project.org/config/
nlog library
.UE
for logging.\&
.IP
Nlog is very flexible and has many available output targets, formats, and fields.\&
.IP
The default configuration provided with a new installation of \*[SIAZ] defines a
console (stdout) target, with colored output, based on message severity,
which is enabled by default, and set to INFO level.\&
It also defines two file targets \(em one for all log lines, set at INFO level,
and one for log lines with WARN or higher severity.\&
.IP
The console target is used when running \*[SIAZ] manually,
and is captured by systemd and written to the system journal,
when running as a systemd service.\&
.IP
The default base destination directory for the file log targets is
.I /var/log/\*[SIAZ]\fR.\&
.IP
The general log files are written to the \fIall\fP sub-directory, named \fI\*[SIAZLC]-YYYY-MM-DD.log\fP.\&
.IP
The error log files are written to the \fIerror\fP sub-directory, named \fI\*[SIAZLC]-error-YYYY-MM-DD.log\fP.\&
.SS CONFIGURATION FILE SCHEMA
.PP
This document describes the settings and general layout of the JSON configuration files in natural language.\&
Formal JSON schema documents are provided for
.I \*[SCONF]
and
.I \*[SLCONF]
in the
.I /usr/local/share/\*[SIAZ]
directory, named
.I /usr/local/share/\*[SIAZ]/\*[SIAZ].schema.json
and
.I /usr/local/share/\*[SIAZ]/\*[SIAZ].local.schema.json\fR.\&
.PP
Changes to the schema documents are not supported.\&
.PP
The general schema of the two configuration files is identical, except for which elements are defined as \(dqrequired\(dq.\&
.PP
This document will describe settings by using
.UR https://www.rfc-editor.org/rfc/rfc6901
JSON pointer notation
to identify configuration element keys.\&
.TP
.B General rules for configuration element values
.RS
.TP
.B \(bu boolean
Boolean values must be specified as
.B true
or
.B false\fR,
without quotation marks.\&
.TQ
.B \(bu numeric
Numeric values must be specified as integer values, without quotation marks.\&
.IP
Additional restrictions on or practical ranges of the values of numeric settings may exist, and will be noted, when applicable.\&
.TQ
.B \(bu time
Time values must be specified as a quoted string, in 24-hour format, with leading zeros for the hour, minute, and seconds portions, if less than 10, and may optionally include fractional seconds up to 7 decimal places.\&
For example: "01:23:45.1234567"
.IP
These values are generally used by \*[SIAZ] as .net TimeOnly types and must be parseable as such.\&
See
.UR https://learn.microsoft.com/en-us/dotnet/api/system.timeonly?view=net-7.0
Microsoft .net 7.0 TimeOnly documentation.
.TQ
.B \(bu DateTimeOffset format string
DateTimeOffset format string values, such as the \fBTimestampFormatString\fP in template formatting settings, must be specified as a quoted string that follows the rules documented for
.UR https://learn.microsoft.com/en-us/dotnet/standard/base-types/standard-date-and-time-format-strings
date and time format strings.\&
.UE
Care must be taken to ensure proper escaping of characters such as the time component separator (:) and the escape character (\\) itself.\&
.TQ
.B \(bu string
General string values must be specified as quoted strings.\&
.IP
Additional restrictions on length or allowed characters may exist and will be noted, when applicable.\&
.TQ
.B \(bu object
Object values must be specified as JSON objects, which are a collection of \fBstring\fP keys and values of a specified type, all enclosed in curly braces ( { and } ).\&
.IP
The required elements of object types will be provided in their respective sections.\&
.TQ
.B \(bu dictionary
Dictionary types are object types, for which there is a string key and an object value, with each key/object pair separated by a comma.\&
.RE
.TQ
.B GLobal configuration elements
.RS
.TP
.B /TakeSnapshots
.RS
.TP
Type: boolean
.IP
This setting enables or disables the execution of the code that handles creating new snapshots.\&
.TQ
Values:
.RS
.TP 4
.B \(bu true
Enables execution of code that handles creating new snapshots.\&
Does NOT imply taking snapshots for any dataset.\&
A dataset must have appropriate properties set for a snapshot to be taken.\&
See
.B snapsinazfs-zfsprops(7)\fR.\&
.TQ 4
.B \(bu false
Disables execution of code that handles creating new snapshots.\&
This prevents snapshots from being created for ALL datasets,
regardless of thier configured ZFS properties.\&
.RE
.TQ
Command-line options:
.RS
.TP 4
.B \-\-take\-snapshots
Overrides this setting, forcing its value to \fBtrue\fP.
.TQ 4
.B \-\-no\-take\-snapshots
Overrides this setting, forcing its value to \fBfalse\fP.
.RE
.RE
.
.
.TQ
.B /PruneSnapshots
.RS
.TP
Type: boolean
.IP
This setting enables or disables the execution of the code that handles checking for expiration of existing snapshots and pruning of snapshots that have expired.\&
.TQ
Values:
.RS
.TP 4
.B \(bu true
Enables execution of code that handles checking for expiration of existing snapshots and pruning of snapshots that have expired.\&
Does NOT imply pruning snapshots for any dataset.\&
A dataset must have appropriate properties set for any of its snapshots to be pruned.\&
See
.B snapsinazfs-zfsprops(7)\fR.\&
.TQ 4
.B \(bu false
Disables execution of code that handles checking for expiration of existing snapshots and pruning of snapshots that have expired.\&
This prevents ANY snapshots from being pruned for ALL datasets,
regardless of thier configured ZFS properties.\&
.RE
.TQ
Command-line options:
.RS
.TP 4
.B \-\-prune\-snapshots
Overrides this setting, forcing its value to \fBtrue\fP.
.TQ 4
.B \-\-no\-prune\-snapshots
Overrides this setting, forcing its value to \fBfalse\fP.
.RE
.RE
.
.
.TQ
.B /LocalSystemName
.RS
.TP
Type: string
.IP
This setting defines the value that will be used for the \fB\*[SIAZNS]:sourcesystem\fP ZFS property (\fB\*[SIAZLC]\-zfsprops(7)\fP).\&
.IP
This value may be used by future versions of \*[SIAZ] to allow special handling of snapshots received from another system,
but is not currently used for anything other than setting the sourcesystem property, at this time.\&
.IP
This value MUST be set to a non\-empty, non\-whitespace-only string, and SHOULD be unique among all systems using \*[SIAZ].\&
It is strongly recommended that this setting be set to the fully\-qualified DNS name of the system \*[SIAZ] is running on.\&
.IP
The default value is \fBStandaloneSiazSystem\fP, and is intended as a place\-holder for single\-system deployments only.\&
.RE
.
.
.TQ
.B /DryRun
.RS
.TP
Type: boolean
.IP
This setting controls whether \*[SIAZ] executes in dry run/simulation mode.\&
In dry run mode, all other settings are processed as normal.\&
However, when the time comes to execute a zfs or zpool command that would create or destroy a snapshot, the command is NOT executed.\&
Instead, the operation that \fIwould\fP have been taken is logged at \fBINFO\fP level,
similar to the following sample,
obtained from an actual run of \*[SIAZ] with default settings and DryRun set to true in \*[SLCONF]:
.IP
.B 2023-07-17 00:00:00.0392|INFO  |DRY RUN: Would execute `/usr/local/sbin/zfs snapshot -o snapsinazfs.com:snapshot:name=testpool/vol1@autosnap_2023-07-17_00:00:00_daily -o snapsinazfs.com:snapshot:period=daily -o snapsinazfs.com:snapshot:timestamp=2023-07-17T00:00:00.0392171-07:00 -o snapsinazfs.com:recursion=siaz testpool/vol1@autosnap_2023-07-17_00:00:00_daily`
.IP
While other log output may indicate that a snapshot was successfully created or destroyed, in dry run mode, zfs commands are NOT executed.\&
There is a hard-coded check for the value of the DryRun setting before every call to
\fBzfs set\fP, \fBzfs snapshot\fP, \fBzfs destroy\fP, and \fBzfs inherit\fP in the application.\&
.UR https://github.com/snapsinazfs/snapsinazfs/blob/master/SnapsInAZfs.Interop/Zfs/ZfsCommandRunner/ZfsCommandRunner.cs
See the ZfsCommandRunner source code
.UE
.IP
This is a known cosmetic bug, documented
.UR https://github.com/snapsinazfs/snapsinazfs/issues/11
here
.UE
, and will be addressed before \*[SIAZ] is tagged for stable release.\&
.TQ
Values:
.RS
.TP 4
.B \(bu true
Enables dry run/simulation mode.\&
.TQ 4
.B \(bu false
Operate normally, respecting all other settings and command line options as described in their respective sections.\&
.RE
.TQ
Command-line options:
.RS
.TP 4
.B \-\-dry\-run
Overrides this setting, forcing its value to \fBtrue\fP.
.TQ 4
.B \-\-no\-dry\-run
Overrides this setting, forcing its value to \fBfalse\fP.
.RE
.RE
.
.
.TQ
.B /Daemonize
.RS
.TP
Type: boolean
.IP
This setting controls whether \*[SIAZ] will execute as a daemon or not.\&
.TQ
Values:
.RS
.TP 4
.B \(bu true
\*[SIAZ] will run as a daemon.\&
That is, it will not exit after the first execution of the main loop,
and will continue running and dispatching events on a timer,
as appropriate,
until it receives a \fBSIGINT\fP, \fBSIGKILL\fP, or \fBSIGTERM\fP signal,
either from the service controller or,
if executed on the command-line,
as the ctrl+c key sequence.\&
.IP
The timer that governs execution of configured actions runs on the period specified in the \fBDaemonTimerIntervalSeconds\fP property,
and is aliased to the top of the minute (that is, starting from the exact minute and zero seconds, to the nearest multiple of the timer period).\&
It is not recommended to adjust the value of the timer interval.\&
.IP
The timer monitors for clock/time drift at each elapsed interval and,
if it is more than 500 milliseconds off from a whole-number multiple of its period setting,
will re-adjust as close to the target time as possible.\&
.IP
The timer is very light-weight and there is no appreciable benefit to adjusting it.\&
.TQ 4
.B \(bu false
\*[SIAZ] will run once and then terminate.\&
.RE
.TQ
Command-line options:
.RS
.TP 4
.B \-\-daemonize
Overrides this setting, forcing its value to \fBtrue\fP.
.TQ 4
.B \-\-no\-daemonize
Overrides this setting, forcing its value to \fBfalse\fP.
.RE
.RE
.
.
.TQ
.B /DaemonTimerIntervalSeconds
.RS
.TP
Type: unsigned integer
.IP
This setting specifies the period, in seconds, for the timer used to dispatch events, when running as a daemon.\&
The timer\(aqs period is aliased to the top of the minute (that is, starting from the exact minute and zero seconds, to the nearest multiple of the timer period).\&
For example, with the default setting of 10,
if \*[SIAZ] is launched at 12:34:43, the timer will adjust itself to 7 seconds,
so that it elapses at 12:34:50,
and then will adjust itself back to 10 seconds,
so that all future intervals elapse on the 00, 10, 20, 30, 40, and 50 second times of every minute.\&
.IP
The timer monitors for clock/time drift at each elapsed interval and,
if it is more than 500 milliseconds off from a whole-number multiple of its period setting,
will re-adjust as close to the target time as possible.\&
.IP
The timer is very light-weight and there is no appreciable benefit to adjusting it.\&
.IP
.B It is not recommended to adjust the value of the timer interval.\&
.TQ
Restrictions:
The value of this setting MUST be an integer from 1 to 60, inclusive, and SHOULD be a whole number factor of 60.\&
.IP
This value is clamped to the range 1 to 60, inclusive.\&
That is, a value of 0 will be set to 1 and values greater than 60 will be set to 60.\&
.IP
Non-integer values or negative values are invalid and may cause a configuration parse error or undefined behavior.\&
.IP
While it is possible to specify values that are greater than 30, this may have unexpected results and is not recommended.\&
.IP
In general, it is not useful to adjust this value from its default of 10,
as it will have no appreciable impact on system resources,
and reduces the timer\(aqs ability to correct for drift.\&
.TQ
Command-line options:
.RS
.TP 4
.B \-\-daemon-timer-interval
Overrides this setting, forcing its value to provided value.\&
The same value clamping rules are followed for the command-line option as for the configuration file setting.\&
.RE
.RE
.
.
.TQ
.B /ZfsPath
.RS
.TP
Type: string
.IP
This setting MUST be a resolveable path to the zfs utility or a symbolic link to the zfs utility.\&
.IP
Any user accounts used to execute \*[SIAZ] must have execute permissions to this path and,
if zfs permissions are in use,
must also be permitted to run
\fBzfs list\fP and \fBzfs get\fP (for ALL datasets),
\fBzfs snapshot\fP (for datasets configured to take snapshots),
\fBzfs destroy\fP (for snapshot pruning),
and \fBzfs inherit\fP (configuration console only),
to execute all possible zfs utility functions \*[SIAZ] is capable of running.\&
.RE
.
.
.TQ
.B /ZpoolPath
.RS
.TP
Type: string
.IP
This setting MUST be a resolveable path to the zpool utility or a symbolic link to the zfs utility.\&
.IP
Any user accounts used to execute \*[SIAZ] must have execute permissions to this path and,
if zfs permissions are in use,
must also be permitted to run
\fBzpool list\fP, \fBzpool get\fP, and \fBzpool set\fP, for ALL pools,
to execute all possible zpool utility functions \*[SIAZ] is capable of running.\&
.RE
.
.
.TQ
.B /Templates
.RS
.TP
Type: dictionary
.IP
This is a dictionary where the keys are string names of templates,
and the values for those keys are objects of template type, described in the
.B \(dqTemplate Objects\(dq
section below.\&
.RE
.RE
.TQ
.B Template Objects
A template object defines common naming and timing settings that should be used for creating snapshots on any dataset the template is applied to.\&
Template names are the string keys of the Templates dictionary, and have no hard restrictions,
though a practical limit of 20 printable 7-bit ASCII characters is suggested.\&
.IP
A template that is defined both in \fI\*[SCONF]\fP and in \fI[\*[SLCONF]\fP will have a final value equal to the base configuration,
with any values specified in the local configuration overriding the base copy.\&
Thus, it is possible to fully define a template object in the base configuration,
such as the included \(dqdefault\(dq template,
and then only configure the specific settings you wish to override, in your local configuration.\&
Because of this design, there is no need to modify the base configuration,
outside of multi-instance/multi-configuration setups, where a common but non-default base configuration is desired.\&
.IP
However, as with all other configuration elements,
the recommended and only officially supported method of modifying, creating, or deleting template objects is
via the configuration console (\fB\-\-config\-console\fP).\&
Using the configuration console will ensure that all changes to your configuration,
including templates, are correct, consistent, and fully\-defined.\&
One particular protection the configuration console provides is that,
if you try to remove a template that any ZFS dataset is currently configured to use,
you will be alerted of that fact and barred from removing the template,
until it is no longer in use,
to prevent errors in execution of \*[SIAZ] caused by missing templates,
the result of which is new snapshots not being taken on any affected dataset.\&
.IP
Because of this protection, you are \fBSTRONGLY\fP advised not to create or remove templates manually in the configuration files.\&
.IP
The JSON schema document formally describing the schema of a template object is located at \fI/usr/local/share/\*[SIAZ]/\*[SIAZ].template.schema.json\fP
.PS 12p
.IP
.B Use the configuration console.\&
.TP
Template Object Properties:
.RS
.TP
.B /Templates/TemplateName/Formatting
.RS
.TP
Type: object
.IP
The Formatting object of a template controls how names of snapshots are composed for datasets the template is applied to.\&
These settings do not affect snapshot pruning.\&
.TQ
Properties:
.RS
.TP
.B /Templates/TemplateName/Formatting/ComponentSeparator
.RS
.TP
Type: string
.IP
This is the string that is used to separate each component of a snapshot name, when creating new snapshots.\&
.IP
.TQ
Restrictions:
.IP
ZFS imposes limits on all identifiers.\&
This string must be composed of printable 7-bit ASCII characters that satisfy the regular expression [A\-Za\-z0\-9_\.: \-]{0,2}.\&
Current versions of ZFS, as of this writing, use a hard-coded limit of 255 7-bit ASCII characters for the fully\-qualified name of any object.\&
The length limit on this string is imposed by \*[SIAZ], to help keep snapshot names under ZFS\(aq hard-coded identifier length limit.\&
.IP
The default and suggested value is a single underscore character (_).\&
This is the same value used by sanoid, and, along with other default values in this section,
enables limited cross-compatibility between the two applications.\&
.RE
.
.
.TQ
.B /Templates/TemplateName/Formatting/Prefix
.RS
.TP
Type: string
.IP
This is the string used as the first component of a snapshot name, immediately following the @ symbol.\&
.IP
.TQ
Restrictions:
.IP
ZFS imposes limits on all identifiers.\&
This string must start with an alphanumeric character, and can be followed by any characters that staisfy the regular expression \fB([A\-Za\-z0\-9_\.:\-]*)\fP
.IP
While whitespace is legal in ZFS identifiers, after the first character of each component, \*[SIAZ] does not currently support snapshots with whitespace in their names.\&
.IP
A practical length limit for this string is less than 20 characters, though longer values are allowed.\&
.IP
The default and suggested value is the string \(dqautosnap\(dq.\&
This is the same value used by sanoid, and, along with other default values in this section,
enables limited cross-compatibility between the two applications.\&
.RE
.
.
.TQ
.B /Templates/TemplateName/Formatting/TimestampFormatString
.RS
.TP
Type: DateTimeOffset format string
.IP
This format string is used to transform the timestamp for a new snapshot for use as the second component of a snapshot name.\&
.IP
.TQ
Restrictions:
This string must be a valid and properly\-escaped DateTimeOffset format string, as described in the general rules for configuration element values, above.\&
.IP
The default properly-escaped and suggested value is the string \(dqyyyy\-MM\-dd_HH\\\\:mm\\\\:ss\(dq.\&
This results in the same output as sanoid, and, along with other default values in this section,
enables limited cross-compatibility between the two applications.\&
.RE
.
.
.TQ
.B /Templates/TemplateName/Formatting/FrequentSuffix
.RS
.TP
Type: string
.IP
This string is used as the final component of a \(dqfrequent\(dq snapshot name.\&
.IP
.TQ
Restrictions:
This string must be valid per the ZFS identifier rules, and must not contain whitespace.\&
.IP
A practical length limit is less than 20 characters, though longer values are allowed.\&
.IP
The default and suggested value is the string \(dqfrequently\(dq.\&
This is the same value used by sanoid, and, along with other default values in this section,
enables limited cross-compatibility between the two applications.\&
.RE
.
.
.TQ
.B /Templates/TemplateName/Formatting/HourlySuffix
.RS
.TP
Type: string
.IP
This string is used as the final component of an \(dqhourly\(dq snapshot name.\&
.IP
.TQ
Restrictions:
This string must be valid per the ZFS identifier rules, and must not contain whitespace.\&
.IP
A practical length limit is less than 20 characters, though longer values are allowed.\&
.IP
The default and suggested value is the string \(dqhourly\(dq.\&
This is the same value used by sanoid, and, along with other default values in this section,
enables limited cross-compatibility between the two applications.\&
.RE
.
.
.TQ
.B /Templates/TemplateName/Formatting/DailySuffix
.RS
.TP
Type: string
.IP
This string is used as the final component of a \(dqdaily\(dq snapshot name.\&
.IP
.TQ
Restrictions:
This string must be valid per the ZFS identifier rules, and must not contain whitespace.\&
.IP
A practical length limit is less than 20 characters, though longer values are allowed.\&
.IP
The default and suggested value is the string \(dqdaily\(dq.\&
This is the same value used by sanoid, and, along with other default values in this section,
enables limited cross-compatibility between the two applications.\&
.RE
.
.
.TQ
.B /Templates/TemplateName/Formatting/WeeklySuffix
.RS
.TP
Type: string
.IP
This string is used as the final component of a \(dqweekly\(dq snapshot name.\&
.IP
.TQ
Restrictions:
This string must be valid per the ZFS identifier rules, and must not contain whitespace.\&
.IP
A practical length limit is less than 20 characters, though longer values are allowed.\&
.IP
The default and suggested value is the string \(dqweekly\(dq.\&
This is the same value used by sanoid, and, along with other default values in this section,
enables limited cross-compatibility between the two applications.\&
.RE
.
.
.TQ
.B /Templates/TemplateName/Formatting/MonthlySuffix
.RS
.TP
Type: string
.IP
This string is used as the final component of a \(dqmonthly\(dq snapshot name.\&
.IP
.TQ
Restrictions:
This string must be valid per the ZFS identifier rules, and must not contain whitespace.\&
.IP
A practical length limit is less than 20 characters, though longer values are allowed.\&
.IP
The default and suggested value is the string \(dqmonthly\(dq.\&
This is the same value used by sanoid, and, along with other default values in this section,
enables limited cross-compatibility between the two applications.\&
.RE
.
.
.TQ
.B /Templates/TemplateName/Formatting/YearlySuffix
.RS
.TP
Type: string
.IP
This string is used as the final component of a \(dqyearly\(dq snapshot name.\&
.IP
.TQ
Restrictions:
This string must be valid per the ZFS identifier rules, and must not contain whitespace.\&
.IP
A practical length limit is less than 20 characters, though longer values are allowed.\&
.IP
The default and suggested value is the string \(dqyearly\(dq.\&
This is the same value used by sanoid, and, along with other default values in this section,
enables limited cross-compatibility between the two applications.\&
.RE
.RE
.RE
.TQ
.B /Templates/TemplateName/SnapshotTiming
.RS
.TP
Type: object
.IP
The SnapshotTiming object of a template allows you to fine\-tune the times at which \*[SIAZ] will take specific types of snapshots,
and when existing snapshots will be considered eligible for pruning.\&
.IP
The default settings defined in the \(dqdefault\(dq template, on a new install of \*[SIAZ],
are designed such that all snapshot periods are aligned and,
when created during the same run of \*[SIAZ],
will have the same timestamps (note: they are still individual snapshots).\&
.IP
\*[SIAZ] itself is designed such that snapshots that have the same timestamp are sortable on their period,
with shorter period snapshots being considered "lower" value than longer period snapshots, for the purpose of sorting.\&
This means that, if sorted in ascending order, snapshots with the same timestamp will be ordered as frequent, hourly, daily, weekly, yearly.\&
This is also the order that \*[SIAZ] creates snapshots, when multiple periods are due for the same dataset.\&
Therefore, consistency is maintained between how \*[SIAZ] views a snapshot's order and how ZFS views it.\&
.IP
This also has the effect that longer period snapshots taken during the same run of
\*[SIAZ] will \(dqcontain\(dq the shorter period snapshots taken during that run,
since they are taken immediately after the shorter period snapshots with the same timestamp.\&
.TQ
Properties:
.RS
.TP
.B /Templates/TemplateName/SnapshotTiming/FrequentPeriod
.RS
.TP
Type: unsigned integer
.IP
This setting is the interval, in minutes, between \(dqfrequent\(dq snapshots,
for datasets using this template.\&
.IP
.TQ
Restrictions:
.IP
This setting MUST be a positive integer less than 59, and SHOULD be a whole\-number factor of 60.\&
Suggested values are 5, 10, 15, 20, or 30.\&
.IP
Values over 30, while legal, will have the result of only two \(dqfrequent\(dq snapshots being taken per hour,
at the top of the hour (00 minutes) and the minute specified in this setting, and are thus not recommended.\&
For example, a setting of 40 would result in only two frequent snapshots being taken, per hour \(em
one at the top of the hour and one at the 40\-minute mark of that hour.\&
.IP
Similar potentially undesired behavior will result from setting this to values that are not a factor of 60,
as they will result in 60 mod [value] + 1 frequent snapshots per hour.\&
For example, a setting of 16 will result in 60 mod 16 + 1 = 4 frequent snapshots per hour, at the 00, 16, 32, and 48 minute marks,
leaving you with 3 snapshots separated by 16 minutes, and one separated by 12 minutes.\&
.IP
Values less than or equal to 30 result in 60 mod [value] snapshots per hour.\&
For example, a setting of 15 (the default) results in 4 frequent snapshots per hour, at the 00, 15, 30, and 45 minute marks.\&
.IP
If you use the configuration console to configure templates, as is recommended,
you will only be offered a limited set of suggested values for this setting, to keep things intuitive.\&
.IP
Values less than 5 are not recommended.\&
.IP
Values less than 1 or greater than 59 are not valid and will clamp to the range 1 to 59, inclusive.\&
The value 60 is excluded because it is meaningless, as it would simply be another hourly snapshot.\&
.IP
When running under systemd or when \fBDaemonize\fP is \fBtrue\fP,
\*[SIAZ] also uses this value as part of its determination of when to actually execute the main program loop.\&
The calculation performed to determine execution period is taking the greatest common factor of the values of this
property for all configured templates (call this value \(dq\fBgcf\fP\(dq for this paragraph).
When the timer ticks,
if the current time is greater than or equal to the last run time plus \fBgcf\fP minutes,
set the last run time to the current time, execute the main program loop,
and then wait for the next timier tick.\&
.IP
When running at the command line when \fBDaemonize\fP is \fBfalse\fP,
this calculation is not performed,
and the main program loop is unconditionally executed.\&
However, since you can set different settings per template,
you should ensure,
if you are running \*[SIAZ] from a cron job or other scheduled single\-execution method,
that the timing of that cron job or other scheduled execution aligns with the timing parameters you have defined in your \*[SIAZ] settings.\&
Otherwise, snapshots (especially frequent snapshots) will not be taken when you expect them to be taken.\&
The proper method of determining that maximum interval for
cron or other scheduled executions of \*[SIAZ]
is to take the greatest common factor of all configured templates,
just as \*[SIAZ] does, when run as a daemon.\&
.IP
If you follow the recommendations for values in this document,
your calculated gcf will be a whole\-number factor of 60 and will result in intuitive behavior.\&
If you have not followed the recommendations for values in this document,
your calculated gcf may not be a whole\-number factor of 60.\&
If this is the case, it is \fBSTRONGLY\fP recommended that you adjust this value for your templates to achieve a gcf that is a whole\-number factor of 60.
.IP
For reference, all whole\-number factors of 60 less than 60 itself are 1, 2, 3, 4, 5, 6, 10, 12, 15, 20, and 30.\&
.IP
Configurations that result in a gcf not in the above set of factors of 60 are not supported,
and are very likely to result in undesired or unintuitive behavior, when running as a daemon.\&
.IP
Configurations running \*[SIAZ] as a scheduled task,
with a schedule that does not align with your calculated gcf,
are also unsupported and very likely to result in undesired or unintuitive behavior.\&
.RE
.
.
.TQ
.B /Templates/TemplateName/SnapshotTiming/HourlyMinute
.RS
.TP
Type: unsigned integer
.IP
This setting is the time of the hour, in minutes, at which hourly snapshots will be taken for datasets using this template.\&
.IP
The default and suggested setting is 0.\&
.IP
.TQ
Restrictions:
.IP
This setting MUST be an integer in the range 0 to 59, inclusive.\&
.IP
While \*[SIAZ] itself and the creation of new snapshots within ZFS are not resource\-intensive,
pruning of expired snapshots has the potential to cause spikes in IO for any pools involved in a \fBzfs destroy\fP.\&
.IP
This setting enables you to change the time at which hourly snapshots are created, and, thus, when they will expire,
on a per\-template basis.\&
.IP
While this is not likely to be relevant for many systems,
and it is suggested that you simply use the default of 0, in most cases,
it does create the ability to apply templates that are otherwise identical,
except for timing settings, to different datasets, so that you can spread the IO load over the hour,
if you determine, through performance metrics, that this would be advantageous.\&
.IP
This is also potentially useful if you have other software or scripts that run on a schedule,
so that you can adjust the timing of snapshots to better fit the other application\(aqs schedule,
if it is required or desired for the other application to take precedence in scheduling.\&
.RE
.
.
.TQ
.B /Templates/TemplateName/SnapshotTiming/DailyTime
.RS
.TP
Type: time string
.IP
This setting is the time of the day, in 24-hour format, without AM/PM suffix, at which daily snapshots will be taken for datasets using this template.\&
It is legal to specify a fractional seconds component,
but the timer is not configurable to run at sub\-second intervals,
so this mostly has the same effect as simply setting the value to one second later.
.IP
This string MUST be quoted and in the format \(dqHH:mm:ss\(dq, where each component, including the hour, is left\-zero\-filled to a length of 2.\&
For example: \(dq01:23:01\(dq) is a valid (though odd) value.\&
.IP
The default and suggested value is \(dq00:00:00\(dq,
which means taking the daily snapshot at midnight.\&
.RE
.
.
.TQ
.B /Templates/TemplateName/SnapshotTiming/WeeklyDay
.RS
.TP
Type: unsigned integer
.IP
This setting is the zero-indexed day of the week,
where 0 is Sunday,
on which weekly snapshots will be taken.\&
These values are defined by the
.UR https://learn.microsoft.com/en-us/dotnet/api/system.dayofweek?view=net-7.0#fields
DayOfWeek
.UE
enum, in .net 7.0, and are based on a 7\-day week, and are not culture-aware.\&
Thus, 0 is always Sunday, 1 is always Monday, and so on.\&
.TQ
Restrictions:
.IP
This must be an un\-quoted integer value from 0 to 6, inclusive.\&
.IP
The default value in the \(dqdefault\(dq template is 1 (Monday).\&
.RE
.
.
.TQ
.B /Templates/TemplateName/SnapshotTiming/WeeklyTime
.RS
.TP
Type: time string
.IP
This setting is the time of the day, in 24-hour format, without AM/PM suffix,
at which weekly snapshots will be taken,
on the configured WeeklyDay,
for datasets using this template.\&
It is legal to specify a fractional seconds component,
but the timer is not configurable to run at sub\-second intervals,
so this mostly has the same effect as simply setting the value to one second later.\&
.IP
This string MUST be quoted and in the format \(dqHH:mm:ss\(dq, where each component, including the hour, is left\-zero\-filled to a length of 2.\&
For example: \(dq01:23:01\(dq) is a valid (though odd) value.\&
.IP
The default and suggested value is \(dq00:00:00\(dq,
which means taking the weekly snapshot at midnight.\&
.RE
.
.
.TQ
.B /Templates/TemplateName/SnapshotTiming/MonthlyDay
.RS
.TP
Type: unsigned integer
.IP
This setting is the one-indexed day of the month on which monthly snapshots will be taken.\&
.IP
This value is culture\-aware, using the calendar rules defined in the culture of the process \*[SIAZ] is running in.\&
This means that \*[SIAZ] is not required to operate using the Gregorian calendar, for this setting.\&
.IP
If the value of this setting is greater than the number of days in the current month, the value will be clamped to the last day of the current month.\&
This means, for example,
that setting this to 31,
when using the Gregorian calendar,
will result in monthly snapshots being taken on the 30th day of 30\-day months,
the 31st day of 31\-day months,
and the 28th or 29th of February, as appropriate.\&
.IP
The default and suggested value is 1, which means monthly snapshots will be taken on the first day of each month.\&
.RE
.
.
.TQ
.B /Templates/TemplateName/SnapshotTiming/MonthlyTime
.RS
.TP
Type: time string
.IP
This setting is the time of the day, in 24-hour format, without AM/PM suffix,
at which monthly snapshots will be taken,
on the configured MonthlyDay,
for datasets using this template.\&
It is legal to specify a fractional seconds component,
but the timer is not configurable to run at sub\-second intervals,
so this mostly has the same effect as simply setting the value to one second later.\&
.IP
This string MUST be quoted and in the format \(dqHH:mm:ss\(dq, where each component, including the hour, is left\-zero\-filled to a length of 2.\&
For example: \(dq01:23:01\(dq) is a valid (though odd) value.\&
.IP
The default and suggested value is \(dq00:00:00\(dq,
which means taking monthly snapshot at midnight on MonthlyDay.\&
.RE
.
.
.TQ
.B /Templates/TemplateName/SnapshotTiming/YearlyMonth
.RS
.TP
Type: unsigned integer
.IP
This setting is the one-indexed day of the month in which yearly snapshots will be taken.\&
.IP
This value is culture\-aware, using the calendar rules defined in the culture of the process \*[SIAZ] is running in.\&
This means that \*[SIAZ] is not required to operate using the Gregorian calendar, for this setting.\&
.IP
When using the configuration console,
you will be presented with the \fBnames\fP of the months,
in system-local culture and language.\&
Selection of a named month value from the available options will result in the appropriate numeric value being used,
when saving the configuration.\&
.IP
As long as two different systems are using the same calendar,
this value is portable between systems, regardless of language differences.\&
For example,
if a user selects the value \(dqFebruary\(dq on a system in the en_US culture,
and then transfers that configuration file to a system using the es_MX culture,
the second system will correctly interpret the month as \(dqFebrero\(dq and operate as expected, in local time.\&
.TQ
Restrictions:
.IP
This must be an un\-quoted integer value from 1 to n, inclusive, where n is the number of months in the calendar defined by the system locale/culture.\&
Values outside this range are invalid and will result in failure or undefined behavior.\&
.IP
As with all settings,
it is strongly recommended that you use the configuration console to alter this setting,
to ensure consistent and correct values are used.\&
.IP
The default value in the \(dqdefault\(dq template is 1 (The first month of the year, in all calendars).\&
.RE
.
.
.TQ
.B /Templates/TemplateName/SnapshotTiming/YearlyDay
.RS
.TP
Type: unsigned integer
.IP
This setting is the one-indexed day of the YearlyMonth on which yearly snapshots will be taken.\&
.IP
This value is culture\-aware, using the calendar rules defined in the culture of the process \*[SIAZ] is running in.\&
This means that \*[SIAZ] is not required to operate using the Gregorian calendar, for this setting.\&
.IP
If the value of this setting is greater than the number of days in the configured YearlyMonth, the value will be clamped to the last day of that month.\&
.IP
The default and suggested value is 1, which means yearly snapshots will be taken on the first day of YearlyMonth.\&
.RE
.
.
.TQ
.B /Templates/TemplateName/SnapshotTiming/YearlyTime
.RS
.TP
Type: time string
.IP
This setting is the time of the day, in 24-hour format, without AM/PM suffix,
at which yearly snapshots will be taken,
on the configured YearlyDay of the configured YearlyMonth,
for datasets using this template.\&
It is legal to specify a fractional seconds component,
but the timer is not configurable to run at sub\-second intervals,
so this mostly has the same effect as simply setting the value to one second later.\&
.IP
This string MUST be quoted and in the format \(dqHH:mm:ss\(dq, where each component, including the hour, is left\-zero\-filled to a length of 2.\&
For example: \(dq01:23:01\(dq) is a valid (though odd) value.\&
.IP
The default and suggested value is \(dq00:00:00\(dq,
which means taking the yearly snapshot at midnight on YearlyDay of YearlyMonth.\&
.RE
.RE
.RE
(End of Template Object Properties)
.RE
.PP
(End of Configuration File Schema)
.SH EXAMPLES
.PP
Provided here are copies of the original text of \fI\*[SCONF]\fP and \fI\*[SLCONF]\fP, for reference,
as well as other sample configurations,
demonstrating potential common scenarios.\&
.SS Original \*[SCONF]
This is the original content of \fI\*[SCONF]\fP, as provided in a new install of \*[SIAZ].\&
Nodes beginning with the $ symbol are metadata and are not parsed by \*[SIAZ] and do not affect its operation.\&
.EX
{
  "$schema": "SnapsInAZfs.schema.json",
  "$id": "SnapsInAZfs.json",
  "$comments": "Default settings for SnapsInAZfs. It is not recommended to modify this file. Customized settings should be specified in /etc/SnapsInAZfs/SnapsInAZfs.local.json",
  "TakeSnapshots": false,
  "PruneSnapshots": false,
  "Daemonize": false,
  "DaemonTimerIntervalSeconds": 10,
  "ZfsPath": "/usr/local/sbin/zfs",
  "ZpoolPath": "/usr/local/sbin/zpool",
  "DryRun": false,
  "LocalSystemName": "StandaloneSiazSystem",
  "Monitoring": {
    "Nagios": {
      "$comments": "Nagios-specific monitoring options",
      "MonitorType": "Nagios",
      "Capacity": false,
      "Health": false,
      "Snapshots": false
    }
  },
  "Templates": {
    "default": {
      "Formatting": {
        "ComponentSeparator": "_",
        "Prefix": "autosnap",
        "TimestampFormatString": "yyyy-MM-dd_HH\\:mm\\:ss",
        "FrequentSuffix": "frequently",
        "HourlySuffix": "hourly",
        "DailySuffix": "daily",
        "WeeklySuffix": "weekly",
        "MonthlySuffix": "monthly",
        "YearlySuffix": "yearly"
      },
      "SnapshotTiming": {
        "FrequentPeriod": 15,
        "HourlyMinute": 0,
        "DailyTime": "00:00:00",
        "WeeklyDay": 1,
        "WeeklyTime": "00:00:00",
        "MonthlyDay": 1,
        "MonthlyTime": "00:00:00",
        "YearlyMonth": 1,
        "YearlyDay": 1,
        "YearlyTime": "00:00:00"
      }
    }
  }
}
.EE
.SS Original \*[SLCONF]
This is the original content of \fI\*[SLCONF]\fP, as provided in a new install of \*[SIAZ].\&
Nodes beginning with the $ symbol are metadata and are not parsed by \*[SIAZ] and do not affect its operation.\&
.EX
{
  "$schema": "SnapsInAZfs.local.schema.json",
  "$id": "SnapsInAZfs.local.json",
  "$comments": "Values specified here supersede and extend the base configuration in SnapsInAZfs.json.",
  "ZfsPath": "/usr/local/sbin/zfs",
  "ZpoolPath": "/usr/local/sbin/zpool",
  "TakeSnapshots": false,
  "PruneSnapshots": false,
  "DryRun": false,
  "LocalSystemName": "StandaloneSiazSystem",
  "Daemonize": false,
  "Monitoring": {
    "Nagios": {
      "$comments": "Nagios-specific monitoring options",
      "MonitorType": "Nagios",
      "Capacity": false,
      "Health": false,
      "Snapshots": false
    }
  },
  "Templates": {
    "production": {
      "Formatting": {
        "ComponentSeparator": "_",
        "Prefix": "autosnap",
        "TimestampFormatString": "yyyy-MM-dd_HH\\:mm\\:ss",
        "FrequentSuffix": "frequently",
        "HourlySuffix": "hourly",
        "DailySuffix": "daily",
        "WeeklySuffix": "weekly",
        "MonthlySuffix": "monthly",
        "YearlySuffix": "yearly"
      },
      "SnapshotTiming": {
        "FrequentPeriod": 15,
        "HourlyMinute": 0,
        "DailyTime": "00:00:00",
        "WeeklyDay": 1,
        "WeeklyTime": "00:00:00",
        "MonthlyDay": 1,
        "MonthlyTime": "00:00:00",
        "YearlyMonth": 1,
        "YearlyDay": 1,
        "YearlyTime": "00:00:00"
      }
    }
  }
}
.EE
.SH SEE ALSO
.TP
.B \*[SIAZLC](8)
.TQ
.B \*[SIAZLC]\-zfsprops(7)
.TQ
.B \*[SIAZLC]\-config\-console(8)
