name: "Latest 'release' Tag Status"

on:
  push:
    tags: [ "release-*" ]

jobs:
  build-and-test:
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout tag
      uses: actions/checkout@v6
    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: 10.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore --configuration Release-R2R
    - name: Test
      run: dotnet test --no-restore --configuration Release-R2R --verbosity minimal
