<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net9.0</TargetFrameworks>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
    <LangVersion>13</LangVersion>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <Configurations>Debug;Release;Release-R2R;Debug-Windows;Debug-NoZFS</Configurations>
    <Platforms>x64</Platforms>
    <DebugType>embedded</DebugType>
    <CheckForOverflowUnderflow>True</CheckForOverflowUnderflow>
    <RuntimeIdentifiers>linux-x64;win-x64</RuntimeIdentifiers>
    <RootNamespace>SnapsInAZfs</RootNamespace>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|x64'">
    <DefineConstants>$(DefineConstants);JETBRAINS_ANNOTATIONS</DefineConstants>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug-Windows|x64'">
    <DefineConstants>$(DefineConstants);WINDOWS;JETBRAINS_ANNOTATIONS</DefineConstants>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|x64'">
    <ContinuousIntegrationBuild>True</ContinuousIntegrationBuild>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release-R2R|x64'">
    <Optimize>True</Optimize>
    <GenerateDocumentationFile>False</GenerateDocumentationFile>
    <PublishReadyToRun>True</PublishReadyToRun>
    <PublishSingleFile>True</PublishSingleFile>
    <RuntimeIdentifiers>linux-x64</RuntimeIdentifiers>
    <TieredCompilation>False</TieredCompilation>
    <ContinuousIntegrationBuild>True</ContinuousIntegrationBuild>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Interop\Zfs\Structs\**" />
    <Compile Remove="Interop\Zfs\Native\**" />
    <Compile Remove="Interop\Libc\**" />
  </ItemGroup>

  <ItemGroup>
    <Compile Include="Interop\Libc\Enums\Errno.cs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="JetBrains.Annotations" Version="2025.2.0" />
    <PackageReference Include="NLog" Version="6.0.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SnapsInAZfs.Settings\SnapsInAZfs.Settings.csproj" />
  </ItemGroup>
  
  <ItemGroup>
    <Using Include="NLog" />
    <Using Include="SnapsInAZfs.Settings" />
  </ItemGroup>
  
  <!-- C stdlib typedefs -->
  <ItemGroup>
    <Using Alias="__uid_t" Include="System.UInt32" />
    <Using Alias="__gid_t" Include="System.UInt32" />
    <Using Alias="__ino_t" Include="System.UInt64" />
    <Using Alias="__dev_t" Include="System.UInt64" />
    <Using Alias="__ino64_t" Include="System.UInt64" />
    <Using Alias="__nlink_t" Include="System.UInt64" />
    <Using Alias="__blksize_t" Include="System.Int64" />
    <Using Alias="__blkcnt_t" Include="System.Int64" />
    <Using Alias="__blkcnt64_t" Include="System.Int64" />
    <Using Alias="__off_t" Include="System.Int64" />
    <Using Alias="__off64_t" Include="System.Int64" />
    <Using Alias="__mode_t" Include="System.IO.UnixFileMode" />
    <Using Alias="timespec" Include="System.Int64" />
    <Using Alias="__time_t" Include="System.Int64" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="SnapsInAZfs.Settings.Tests" />
  </ItemGroup>

</Project>