<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <Configurations>Debug;Release;Release-R2R;Debug-Windows;Debug-NoZFS</Configurations>
    <Platforms>x64</Platforms>
    <DebugType>embedded</DebugType>
    <CheckForOverflowUnderflow>True</CheckForOverflowUnderflow>
    <RuntimeIdentifiers>linux-x64;win-x64</RuntimeIdentifiers>
    <DisableRuntimeMarshaling>True</DisableRuntimeMarshaling>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|x64'">
    <DefineConstants>$(DefineConstants);JETBRAINS_ANNOTATIONS</DefineConstants>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug-Windows|x64'">
    <DefineConstants>$(DefineConstants);WINDOWS;JETBRAINS_ANNOTATIONS</DefineConstants>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|x64'">
    <ContinuousIntegrationBuild>True</ContinuousIntegrationBuild>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release-R2R|x64'">
    <Optimize>True</Optimize>
    <GenerateDocumentationFile>False</GenerateDocumentationFile>
    <PublishReadyToRun>True</PublishReadyToRun>
    <PublishSingleFile>True</PublishSingleFile>
    <RuntimeIdentifiers>linux-x64</RuntimeIdentifiers>
    <ContinuousIntegrationBuild>True</ContinuousIntegrationBuild>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="LibAbigail\**" />
    <Compile Remove="LibNvPair\**" />
    <Compile Remove="LibZfsCore\**" />
    <Compile Remove="LibZfs\**" />
    <Compile Remove="Zfs\Structs\**" />
    <Compile Remove="Zfs\Native\**" />
    <Compile Remove="Libc\**" />
    <EmbeddedResource Remove="LibAbigail\**" />
    <EmbeddedResource Remove="LibNvPair\**" />
    <EmbeddedResource Remove="LibZfsCore\**" />
    <EmbeddedResource Remove="LibZfs\**" />
    <None Remove="LibAbigail\**" />
    <None Remove="LibNvPair\**" />
    <None Remove="LibZfsCore\**" />
    <None Remove="LibZfs\**" />
  </ItemGroup>

  <ItemGroup>
    <Compile Include="Libc\Enums\Errno.cs" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SnapsInAZfs.Settings\SnapsInAZfs.Settings.csproj" />
  </ItemGroup>
  
  <ItemGroup>
    <Using Include="NLog" />
    <Using Include="SnapsInAZfs.Settings.Settings" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="SnapsInAZfs.Settings.Tests" />
  </ItemGroup>
  
</Project>
