
//------------------------------------------------------------------------------

//  <auto-generated>
//      This code was generated by:
//        TerminalGuiDesigner v1.0.24.0
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// -----------------------------------------------------------------------------
namespace Sanoid.ConfigConsole {
    using System;
    using Terminal.Gui;
    
    
    public partial class TemplateConfigurationWindow : Terminal.Gui.Window {
        
        private Terminal.Gui.ColorScheme greyOnBlack;
        
        private Terminal.Gui.ColorScheme whiteOnRed;
        
        private Terminal.Gui.ColorScheme localPropertyTextFieldColorScheme;
        
        private Terminal.Gui.ColorScheme templateConfigurationTextValidateFieldColorScheme;
        
        private Terminal.Gui.ColorScheme inheritedPropertyTextFieldColorScheme;
        
        private Terminal.Gui.ColorScheme localPropertyRadioGroupColorScheme;
        
        private Terminal.Gui.ColorScheme inheritedPropertyRadioGroupColorScheme;
        
        private Terminal.Gui.ColorScheme localPropertyListViewColorScheme;
        
        private Terminal.Gui.ColorScheme inheritedPropertyListViewColorScheme;
        
        private Terminal.Gui.ColorScheme tgDefault;
        
        private Terminal.Gui.ColorScheme allBlackColorScheme;
        
        private Terminal.Gui.ColorScheme blackAndWhiteColorScheme;
        
        private Terminal.Gui.ColorScheme midnightColorScheme;
        
        private Terminal.Gui.ColorScheme whiteOnBlue;
        
        private Terminal.Gui.ColorScheme treeAndListViewColorScheme;
 
                private Terminal.Gui.LineView templateConfigurationDividerLine;
        
        private Terminal.Gui.FrameView templateConfigurationTemplatePropertiesFrame;
        
        private Terminal.Gui.FrameView templateConfigurationSnapshotNamingFrame;
        
        private Terminal.Gui.Label templateConfigurationPropertiesNamingComponentSeparatorLabel;
        
        private Terminal.Gui.TextValidateField templateConfigurationPropertiesNamingComponentSeparatorValidateField;
        
        private Terminal.Gui.Label templateConfigurationPropertiesNamingPrefixLabel;
        
        private Terminal.Gui.TextValidateField templateConfigurationPropertiesNamingPrefixTextValidateField;
        
        private Terminal.Gui.Label templateConfigurationPropertiesNamingTimestampFormatLabel;
        
        private Terminal.Gui.TextField templateConfigurationPropertiesNamingTimestampFormatTextField;
        
        private Terminal.Gui.Label templateConfigurationPropertiesNamingFrequentSuffixLabel;
        
        private Terminal.Gui.TextValidateField templateConfigurationPropertiesNamingFrequentSuffixTextValidateField;
        
        private Terminal.Gui.Label templateConfigurationPropertiesNamingHourlySuffixLabel;
        
        private Terminal.Gui.TextValidateField templateConfigurationPropertiesNamingHourlySuffixTextValidateField;
        
        private Terminal.Gui.Label templateConfigurationPropertiesNamingDailySuffixLabel;
        
        private Terminal.Gui.TextValidateField templateConfigurationPropertiesNamingDailySuffixTextValidateField;
        
        private Terminal.Gui.Label templateConfigurationPropertiesNamingWeeklySuffixLabel;
        
        private Terminal.Gui.TextValidateField templateConfigurationPropertiesNamingWeeklySuffixTextValidateField;
        
        private Terminal.Gui.Label templateConfigurationPropertiesNamingMonthlySuffixLabel;
        
        private Terminal.Gui.TextValidateField templateConfigurationPropertiesNamingMonthlySuffixTextValidateField;
        
        private Terminal.Gui.Label templateConfigurationPropertiesNamingYearlySuffixLabel;
        
        private Terminal.Gui.TextValidateField templateConfigurationPropertiesNamingYearlySuffixTextValidateField;
        
        private Terminal.Gui.FrameView templateConfigurationPropertiesSnapshotTimingFrame;
        
        private Terminal.Gui.Label stemplateConfigurationPropertiesTimingFrequentPeriodLabel;
        
        private Terminal.Gui.RadioGroup templateConfigurationPropertiesTimingFrequentPeriodRadioGroup;
        
        private Terminal.Gui.Label templateConfigurationPropertiesTimingHourlyLabel;
        
        private Terminal.Gui.Label templateConfigurationPropertiesTimingHourlyMinuteLabel;
        
        private Terminal.Gui.TextValidateField hourlyMinuteTextValidateField;
        
        private Terminal.Gui.ComboBox comboBox;
        
        private Terminal.Gui.Label templateConfigurationPropertiesTimingDailyLabel;
        
        private Terminal.Gui.Label templateConfigurationPropertiesDailyTimeLabel;
        
        private Terminal.Gui.TimeField dailyTimeTimeField;
        
        private Terminal.Gui.Label templateConfigurationPropertiesWeeklyLabel;
        
        private Terminal.Gui.Label templateConfigurationPropertiesWeeklyLabel2;
        
        private Terminal.Gui.TextValidateField templateConfigurationPropertiesTimingWeeklyDayTextValidateField;
        
        private Terminal.Gui.Label templateConfigurationPropertiesWeeklyTimeLabel;
        
        private Terminal.Gui.TimeField weeklyTimeTimeField;
        
        private Terminal.Gui.Label templateConfigurationPropertiesMonthlyLabel;
        
        private Terminal.Gui.Label templateConfigurationPropertiesMonthlyDayLabel;
        
        private Terminal.Gui.TextValidateField templateConfigurationPropertiesTimingMonthlyDayTextValidateField;
        
        private Terminal.Gui.Label templateConfigurationPropertiesMonthlyTimeLabel;
        
        private Terminal.Gui.TimeField monthlyTimeTimeField;
        
        private Terminal.Gui.Label templateConfigurationPropertiesTimingYearlyLabel;
        
        private Terminal.Gui.Label templateConfigurationPropertiesYearlyMonthLabel;
        
        private Terminal.Gui.TextValidateField templateConfigurationPropertiesTimingYearlyMonthTextValidateField;
        
        private Terminal.Gui.Label templateConfigurationPropertiesYearlyDayLabel;
        
        private Terminal.Gui.TextValidateField templateConfigurationPropertiesTimingYearlyDayTextValidateField;
        
        private Terminal.Gui.Label templateConfigurationPropertiesYearlyTimeLabel;
        
        private Terminal.Gui.TimeField yearlyTimeTimeField;
        
        private Terminal.Gui.Button applyCurrentButton;
        
        private Terminal.Gui.Button templateConfigurationResetCurrentButton;
        
        private Terminal.Gui.FrameView templateConfigurationTemplateListFrame;
        
        private Terminal.Gui.ListView templateConfigurationTemplateListView;
        
        private Terminal.Gui.TextValidateField newTemplateNameTextValidateField;
        
        private Terminal.Gui.Button addTemplateButton;
        
        private Terminal.Gui.Button templateConfigurationDeleteTemplateButton;
        
        private Terminal.Gui.Button templateConfigurationSaveAllButton;
        
        private void InitializeComponent() {
            this.templateConfigurationSaveAllButton = new Terminal.Gui.Button();
            this.templateConfigurationDeleteTemplateButton = new Terminal.Gui.Button();
            this.addTemplateButton = new Terminal.Gui.Button();
            this.newTemplateNameTextValidateField = new Terminal.Gui.TextValidateField();
            this.templateConfigurationTemplateListView = new Terminal.Gui.ListView();
            this.templateConfigurationTemplateListFrame = new Terminal.Gui.FrameView();
            this.templateConfigurationResetCurrentButton = new Terminal.Gui.Button();
            this.applyCurrentButton = new Terminal.Gui.Button();
            this.yearlyTimeTimeField = new Terminal.Gui.TimeField();
            this.templateConfigurationPropertiesYearlyTimeLabel = new Terminal.Gui.Label();
            this.templateConfigurationPropertiesTimingYearlyDayTextValidateField = new Terminal.Gui.TextValidateField();
            this.templateConfigurationPropertiesYearlyDayLabel = new Terminal.Gui.Label();
            this.templateConfigurationPropertiesTimingYearlyMonthTextValidateField = new Terminal.Gui.TextValidateField();
            this.templateConfigurationPropertiesYearlyMonthLabel = new Terminal.Gui.Label();
            this.templateConfigurationPropertiesTimingYearlyLabel = new Terminal.Gui.Label();
            this.monthlyTimeTimeField = new Terminal.Gui.TimeField();
            this.templateConfigurationPropertiesMonthlyTimeLabel = new Terminal.Gui.Label();
            this.templateConfigurationPropertiesTimingMonthlyDayTextValidateField = new Terminal.Gui.TextValidateField();
            this.templateConfigurationPropertiesMonthlyDayLabel = new Terminal.Gui.Label();
            this.templateConfigurationPropertiesMonthlyLabel = new Terminal.Gui.Label();
            this.weeklyTimeTimeField = new Terminal.Gui.TimeField();
            this.templateConfigurationPropertiesWeeklyTimeLabel = new Terminal.Gui.Label();
            this.templateConfigurationPropertiesTimingWeeklyDayTextValidateField = new Terminal.Gui.TextValidateField();
            this.templateConfigurationPropertiesWeeklyLabel2 = new Terminal.Gui.Label();
            this.templateConfigurationPropertiesWeeklyLabel = new Terminal.Gui.Label();
            this.dailyTimeTimeField = new Terminal.Gui.TimeField();
            this.templateConfigurationPropertiesDailyTimeLabel = new Terminal.Gui.Label();
            this.templateConfigurationPropertiesTimingDailyLabel = new Terminal.Gui.Label();
            this.comboBox = new Terminal.Gui.ComboBox();
            this.hourlyMinuteTextValidateField = new Terminal.Gui.TextValidateField();
            this.templateConfigurationPropertiesTimingHourlyMinuteLabel = new Terminal.Gui.Label();
            this.templateConfigurationPropertiesTimingHourlyLabel = new Terminal.Gui.Label();
            this.templateConfigurationPropertiesTimingFrequentPeriodRadioGroup = new Terminal.Gui.RadioGroup();
            this.stemplateConfigurationPropertiesTimingFrequentPeriodLabel = new Terminal.Gui.Label();
            this.templateConfigurationPropertiesSnapshotTimingFrame = new Terminal.Gui.FrameView();
            this.templateConfigurationPropertiesNamingYearlySuffixTextValidateField = new Terminal.Gui.TextValidateField();
            this.templateConfigurationPropertiesNamingYearlySuffixLabel = new Terminal.Gui.Label();
            this.templateConfigurationPropertiesNamingMonthlySuffixTextValidateField = new Terminal.Gui.TextValidateField();
            this.templateConfigurationPropertiesNamingMonthlySuffixLabel = new Terminal.Gui.Label();
            this.templateConfigurationPropertiesNamingWeeklySuffixTextValidateField = new Terminal.Gui.TextValidateField();
            this.templateConfigurationPropertiesNamingWeeklySuffixLabel = new Terminal.Gui.Label();
            this.templateConfigurationPropertiesNamingDailySuffixTextValidateField = new Terminal.Gui.TextValidateField();
            this.templateConfigurationPropertiesNamingDailySuffixLabel = new Terminal.Gui.Label();
            this.templateConfigurationPropertiesNamingHourlySuffixTextValidateField = new Terminal.Gui.TextValidateField();
            this.templateConfigurationPropertiesNamingHourlySuffixLabel = new Terminal.Gui.Label();
            this.templateConfigurationPropertiesNamingFrequentSuffixTextValidateField = new Terminal.Gui.TextValidateField();
            this.templateConfigurationPropertiesNamingFrequentSuffixLabel = new Terminal.Gui.Label();
            this.templateConfigurationPropertiesNamingTimestampFormatTextField = new Terminal.Gui.TextField();
            this.templateConfigurationPropertiesNamingTimestampFormatLabel = new Terminal.Gui.Label();
            this.templateConfigurationPropertiesNamingPrefixTextValidateField = new Terminal.Gui.TextValidateField();
            this.templateConfigurationPropertiesNamingPrefixLabel = new Terminal.Gui.Label();
            this.templateConfigurationPropertiesNamingComponentSeparatorValidateField = new Terminal.Gui.TextValidateField();
            this.templateConfigurationPropertiesNamingComponentSeparatorLabel = new Terminal.Gui.Label();
            this.templateConfigurationSnapshotNamingFrame = new Terminal.Gui.FrameView();
            this.templateConfigurationTemplatePropertiesFrame = new Terminal.Gui.FrameView();
            this.templateConfigurationDividerLine = new Terminal.Gui.LineView();
            this.greyOnBlack = new Terminal.Gui.ColorScheme();
            this.greyOnBlack.Normal = new Terminal.Gui.Attribute(Terminal.Gui.Color.DarkGray, Terminal.Gui.Color.Black);
            this.greyOnBlack.HotNormal = new Terminal.Gui.Attribute(Terminal.Gui.Color.DarkGray, Terminal.Gui.Color.Black);
            this.greyOnBlack.Focus = new Terminal.Gui.Attribute(Terminal.Gui.Color.DarkGray, Terminal.Gui.Color.Black);
            this.greyOnBlack.HotFocus = new Terminal.Gui.Attribute(Terminal.Gui.Color.Black, Terminal.Gui.Color.DarkGray);
            this.greyOnBlack.Disabled = new Terminal.Gui.Attribute(Terminal.Gui.Color.DarkGray, Terminal.Gui.Color.Black);
            this.whiteOnRed = new Terminal.Gui.ColorScheme();
            this.whiteOnRed.Normal = new Terminal.Gui.Attribute(Terminal.Gui.Color.White, Terminal.Gui.Color.BrightRed);
            this.whiteOnRed.HotNormal = new Terminal.Gui.Attribute(Terminal.Gui.Color.White, Terminal.Gui.Color.BrightRed);
            this.whiteOnRed.Focus = new Terminal.Gui.Attribute(Terminal.Gui.Color.White, Terminal.Gui.Color.BrightRed);
            this.whiteOnRed.HotFocus = new Terminal.Gui.Attribute(Terminal.Gui.Color.White, Terminal.Gui.Color.BrightRed);
            this.whiteOnRed.Disabled = new Terminal.Gui.Attribute(Terminal.Gui.Color.White, Terminal.Gui.Color.BrightRed);
            this.localPropertyTextFieldColorScheme = new Terminal.Gui.ColorScheme();
            this.localPropertyTextFieldColorScheme.Normal = new Terminal.Gui.Attribute(Terminal.Gui.Color.DarkGray, Terminal.Gui.Color.Gray);
            this.localPropertyTextFieldColorScheme.HotNormal = new Terminal.Gui.Attribute(Terminal.Gui.Color.White, Terminal.Gui.Color.Gray);
            this.localPropertyTextFieldColorScheme.Focus = new Terminal.Gui.Attribute(Terminal.Gui.Color.Black, Terminal.Gui.Color.White);
            this.localPropertyTextFieldColorScheme.HotFocus = new Terminal.Gui.Attribute(Terminal.Gui.Color.Black, Terminal.Gui.Color.White);
            this.localPropertyTextFieldColorScheme.Disabled = new Terminal.Gui.Attribute(Terminal.Gui.Color.Gray, Terminal.Gui.Color.DarkGray);
            this.templateConfigurationTextValidateFieldColorScheme = new Terminal.Gui.ColorScheme();
            this.templateConfigurationTextValidateFieldColorScheme.Normal = new Terminal.Gui.Attribute(Terminal.Gui.Color.DarkGray, Terminal.Gui.Color.White);
            this.templateConfigurationTextValidateFieldColorScheme.HotNormal = new Terminal.Gui.Attribute(Terminal.Gui.Color.White, Terminal.Gui.Color.DarkGray);
            this.templateConfigurationTextValidateFieldColorScheme.Focus = new Terminal.Gui.Attribute(Terminal.Gui.Color.Black, Terminal.Gui.Color.White);
            this.templateConfigurationTextValidateFieldColorScheme.HotFocus = new Terminal.Gui.Attribute(Terminal.Gui.Color.White, Terminal.Gui.Color.Black);
            this.templateConfigurationTextValidateFieldColorScheme.Disabled = new Terminal.Gui.Attribute(Terminal.Gui.Color.Gray, Terminal.Gui.Color.DarkGray);
            this.inheritedPropertyTextFieldColorScheme = new Terminal.Gui.ColorScheme();
            this.inheritedPropertyTextFieldColorScheme.Normal = new Terminal.Gui.Attribute(Terminal.Gui.Color.DarkGray, Terminal.Gui.Color.Black);
            this.inheritedPropertyTextFieldColorScheme.HotNormal = new Terminal.Gui.Attribute(Terminal.Gui.Color.DarkGray, Terminal.Gui.Color.Black);
            this.inheritedPropertyTextFieldColorScheme.Focus = new Terminal.Gui.Attribute(Terminal.Gui.Color.Black, Terminal.Gui.Color.DarkGray);
            this.inheritedPropertyTextFieldColorScheme.HotFocus = new Terminal.Gui.Attribute(Terminal.Gui.Color.Black, Terminal.Gui.Color.DarkGray);
            this.inheritedPropertyTextFieldColorScheme.Disabled = new Terminal.Gui.Attribute(Terminal.Gui.Color.DarkGray, Terminal.Gui.Color.Black);
            this.localPropertyRadioGroupColorScheme = new Terminal.Gui.ColorScheme();
            this.localPropertyRadioGroupColorScheme.Normal = new Terminal.Gui.Attribute(Terminal.Gui.Color.White, Terminal.Gui.Color.Blue);
            this.localPropertyRadioGroupColorScheme.HotNormal = new Terminal.Gui.Attribute(Terminal.Gui.Color.BrightCyan, Terminal.Gui.Color.Blue);
            this.localPropertyRadioGroupColorScheme.Focus = new Terminal.Gui.Attribute(Terminal.Gui.Color.White, Terminal.Gui.Color.Cyan);
            this.localPropertyRadioGroupColorScheme.HotFocus = new Terminal.Gui.Attribute(Terminal.Gui.Color.BrightCyan, Terminal.Gui.Color.DarkGray);
            this.localPropertyRadioGroupColorScheme.Disabled = new Terminal.Gui.Attribute(Terminal.Gui.Color.White, Terminal.Gui.Color.DarkGray);
            this.inheritedPropertyRadioGroupColorScheme = new Terminal.Gui.ColorScheme();
            this.inheritedPropertyRadioGroupColorScheme.Normal = new Terminal.Gui.Attribute(Terminal.Gui.Color.Black, Terminal.Gui.Color.DarkGray);
            this.inheritedPropertyRadioGroupColorScheme.HotNormal = new Terminal.Gui.Attribute(Terminal.Gui.Color.Black, Terminal.Gui.Color.Gray);
            this.inheritedPropertyRadioGroupColorScheme.Focus = new Terminal.Gui.Attribute(Terminal.Gui.Color.BrightCyan, Terminal.Gui.Color.DarkGray);
            this.inheritedPropertyRadioGroupColorScheme.HotFocus = new Terminal.Gui.Attribute(Terminal.Gui.Color.Cyan, Terminal.Gui.Color.Gray);
            this.inheritedPropertyRadioGroupColorScheme.Disabled = new Terminal.Gui.Attribute(Terminal.Gui.Color.Black, Terminal.Gui.Color.DarkGray);
            this.localPropertyListViewColorScheme = new Terminal.Gui.ColorScheme();
            this.localPropertyListViewColorScheme.Normal = new Terminal.Gui.Attribute(Terminal.Gui.Color.Black, Terminal.Gui.Color.White);
            this.localPropertyListViewColorScheme.HotNormal = new Terminal.Gui.Attribute(Terminal.Gui.Color.Black, Terminal.Gui.Color.Gray);
            this.localPropertyListViewColorScheme.Focus = new Terminal.Gui.Attribute(Terminal.Gui.Color.Black, Terminal.Gui.Color.White);
            this.localPropertyListViewColorScheme.HotFocus = new Terminal.Gui.Attribute(Terminal.Gui.Color.Black, Terminal.Gui.Color.White);
            this.localPropertyListViewColorScheme.Disabled = new Terminal.Gui.Attribute(Terminal.Gui.Color.Black, Terminal.Gui.Color.White);
            this.inheritedPropertyListViewColorScheme = new Terminal.Gui.ColorScheme();
            this.inheritedPropertyListViewColorScheme.Normal = new Terminal.Gui.Attribute(Terminal.Gui.Color.Black, Terminal.Gui.Color.DarkGray);
            this.inheritedPropertyListViewColorScheme.HotNormal = new Terminal.Gui.Attribute(Terminal.Gui.Color.Black, Terminal.Gui.Color.DarkGray);
            this.inheritedPropertyListViewColorScheme.Focus = new Terminal.Gui.Attribute(Terminal.Gui.Color.Black, Terminal.Gui.Color.DarkGray);
            this.inheritedPropertyListViewColorScheme.HotFocus = new Terminal.Gui.Attribute(Terminal.Gui.Color.Black, Terminal.Gui.Color.DarkGray);
            this.inheritedPropertyListViewColorScheme.Disabled = new Terminal.Gui.Attribute(Terminal.Gui.Color.Black, Terminal.Gui.Color.DarkGray);
            this.tgDefault = new Terminal.Gui.ColorScheme();
            this.tgDefault.Normal = new Terminal.Gui.Attribute(Terminal.Gui.Color.White, Terminal.Gui.Color.Blue);
            this.tgDefault.HotNormal = new Terminal.Gui.Attribute(Terminal.Gui.Color.BrightCyan, Terminal.Gui.Color.Blue);
            this.tgDefault.Focus = new Terminal.Gui.Attribute(Terminal.Gui.Color.Black, Terminal.Gui.Color.Gray);
            this.tgDefault.HotFocus = new Terminal.Gui.Attribute(Terminal.Gui.Color.BrightBlue, Terminal.Gui.Color.Gray);
            this.tgDefault.Disabled = new Terminal.Gui.Attribute(Terminal.Gui.Color.Brown, Terminal.Gui.Color.Blue);
            this.allBlackColorScheme = new Terminal.Gui.ColorScheme();
            this.allBlackColorScheme.Normal = new Terminal.Gui.Attribute(Terminal.Gui.Color.Black, Terminal.Gui.Color.Black);
            this.allBlackColorScheme.HotNormal = new Terminal.Gui.Attribute(Terminal.Gui.Color.Black, Terminal.Gui.Color.Black);
            this.allBlackColorScheme.Focus = new Terminal.Gui.Attribute(Terminal.Gui.Color.Black, Terminal.Gui.Color.Black);
            this.allBlackColorScheme.HotFocus = new Terminal.Gui.Attribute(Terminal.Gui.Color.Black, Terminal.Gui.Color.Black);
            this.allBlackColorScheme.Disabled = new Terminal.Gui.Attribute(Terminal.Gui.Color.Black, Terminal.Gui.Color.Black);
            this.blackAndWhiteColorScheme = new Terminal.Gui.ColorScheme();
            this.blackAndWhiteColorScheme.Normal = new Terminal.Gui.Attribute(Terminal.Gui.Color.White, Terminal.Gui.Color.Black);
            this.blackAndWhiteColorScheme.HotNormal = new Terminal.Gui.Attribute(Terminal.Gui.Color.White, Terminal.Gui.Color.Black);
            this.blackAndWhiteColorScheme.Focus = new Terminal.Gui.Attribute(Terminal.Gui.Color.White, Terminal.Gui.Color.Black);
            this.blackAndWhiteColorScheme.HotFocus = new Terminal.Gui.Attribute(Terminal.Gui.Color.White, Terminal.Gui.Color.Black);
            this.blackAndWhiteColorScheme.Disabled = new Terminal.Gui.Attribute(Terminal.Gui.Color.White, Terminal.Gui.Color.Black);
            this.midnightColorScheme = new Terminal.Gui.ColorScheme();
            this.midnightColorScheme.Normal = new Terminal.Gui.Attribute(Terminal.Gui.Color.BrightBlue, Terminal.Gui.Color.Black);
            this.midnightColorScheme.HotNormal = new Terminal.Gui.Attribute(Terminal.Gui.Color.Cyan, Terminal.Gui.Color.Black);
            this.midnightColorScheme.Focus = new Terminal.Gui.Attribute(Terminal.Gui.Color.BrightBlue, Terminal.Gui.Color.Black);
            this.midnightColorScheme.HotFocus = new Terminal.Gui.Attribute(Terminal.Gui.Color.Cyan, Terminal.Gui.Color.Black);
            this.midnightColorScheme.Disabled = new Terminal.Gui.Attribute(Terminal.Gui.Color.DarkGray, Terminal.Gui.Color.Black);
            this.whiteOnBlue = new Terminal.Gui.ColorScheme();
            this.whiteOnBlue.Normal = new Terminal.Gui.Attribute(Terminal.Gui.Color.White, Terminal.Gui.Color.Blue);
            this.whiteOnBlue.HotNormal = new Terminal.Gui.Attribute(Terminal.Gui.Color.White, Terminal.Gui.Color.Blue);
            this.whiteOnBlue.Focus = new Terminal.Gui.Attribute(Terminal.Gui.Color.White, Terminal.Gui.Color.Blue);
            this.whiteOnBlue.HotFocus = new Terminal.Gui.Attribute(Terminal.Gui.Color.White, Terminal.Gui.Color.Blue);
            this.whiteOnBlue.Disabled = new Terminal.Gui.Attribute(Terminal.Gui.Color.White, Terminal.Gui.Color.Cyan);
            this.treeAndListViewColorScheme = new Terminal.Gui.ColorScheme();
            this.treeAndListViewColorScheme.Normal = new Terminal.Gui.Attribute(Terminal.Gui.Color.White, Terminal.Gui.Color.Blue);
            this.treeAndListViewColorScheme.HotNormal = new Terminal.Gui.Attribute(Terminal.Gui.Color.BrightGreen, Terminal.Gui.Color.Blue);
            this.treeAndListViewColorScheme.Focus = new Terminal.Gui.Attribute(Terminal.Gui.Color.White, Terminal.Gui.Color.BrightBlue);
            this.treeAndListViewColorScheme.HotFocus = new Terminal.Gui.Attribute(Terminal.Gui.Color.BrightYellow, Terminal.Gui.Color.Cyan);
            this.treeAndListViewColorScheme.Disabled = new Terminal.Gui.Attribute(Terminal.Gui.Color.Gray, Terminal.Gui.Color.Blue);
            this.Width = 106;
            this.Height = 30;
            this.X = Pos.Center();
            this.Y = Pos.Center();
            this.ColorScheme = this.whiteOnBlue;
            this.Modal = false;
            this.Border.BorderStyle = Terminal.Gui.BorderStyle.Single;
            this.Border.BorderBrush = Terminal.Gui.Color.White;
            this.Border.Effect3D = false;
            this.Border.Effect3DBrush = null;
            this.Border.DrawMarginFrame = true;
            this.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.Title = "Template Configuration";
            this.templateConfigurationDividerLine.Width = 1;
            this.templateConfigurationDividerLine.Height = Dim.Fill(0);
            this.templateConfigurationDividerLine.X = Pos.Right(templateConfigurationTemplateListFrame);
            this.templateConfigurationDividerLine.Y = 0;
            this.templateConfigurationDividerLine.Data = "templateConfigurationDividerLine";
            this.templateConfigurationDividerLine.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.templateConfigurationDividerLine.LineRune = '│';
            this.templateConfigurationDividerLine.Orientation = Terminal.Gui.Graphs.Orientation.Vertical;
            this.Add(this.templateConfigurationDividerLine);
            this.templateConfigurationTemplatePropertiesFrame.Width = 61;
            this.templateConfigurationTemplatePropertiesFrame.Height = Dim.Fill(0);
            this.templateConfigurationTemplatePropertiesFrame.X = Pos.Right(templateConfigurationDividerLine);
            this.templateConfigurationTemplatePropertiesFrame.Y = Pos.Center();
            this.templateConfigurationTemplatePropertiesFrame.Data = "templateConfigurationTemplatePropertiesFrame";
            this.templateConfigurationTemplatePropertiesFrame.Border.BorderStyle = Terminal.Gui.BorderStyle.Single;
            this.templateConfigurationTemplatePropertiesFrame.Border.BorderBrush = Terminal.Gui.Color.White;
            this.templateConfigurationTemplatePropertiesFrame.Border.Effect3D = false;
            this.templateConfigurationTemplatePropertiesFrame.Border.Effect3DBrush = null;
            this.templateConfigurationTemplatePropertiesFrame.Border.DrawMarginFrame = true;
            this.templateConfigurationTemplatePropertiesFrame.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.templateConfigurationTemplatePropertiesFrame.Title = "Properties";
            this.Add(this.templateConfigurationTemplatePropertiesFrame);
            this.templateConfigurationSnapshotNamingFrame.Width = 59;
            this.templateConfigurationSnapshotNamingFrame.Height = 11;
            this.templateConfigurationSnapshotNamingFrame.X = 0;
            this.templateConfigurationSnapshotNamingFrame.Y = 0;
            this.templateConfigurationSnapshotNamingFrame.ColorScheme = this.whiteOnBlue;
            this.templateConfigurationSnapshotNamingFrame.Data = "templateConfigurationSnapshotNamingFrame";
            this.templateConfigurationSnapshotNamingFrame.Border.BorderStyle = Terminal.Gui.BorderStyle.Single;
            this.templateConfigurationSnapshotNamingFrame.Border.BorderBrush = Terminal.Gui.Color.White;
            this.templateConfigurationSnapshotNamingFrame.Border.Effect3D = false;
            this.templateConfigurationSnapshotNamingFrame.Border.Effect3DBrush = null;
            this.templateConfigurationSnapshotNamingFrame.Border.DrawMarginFrame = true;
            this.templateConfigurationSnapshotNamingFrame.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.templateConfigurationSnapshotNamingFrame.Title = "Snapshot Name Formatting";
            this.templateConfigurationTemplatePropertiesFrame.Add(this.templateConfigurationSnapshotNamingFrame);
            this.templateConfigurationPropertiesNamingComponentSeparatorLabel.Width = 4;
            this.templateConfigurationPropertiesNamingComponentSeparatorLabel.Height = 1;
            this.templateConfigurationPropertiesNamingComponentSeparatorLabel.X = 1;
            this.templateConfigurationPropertiesNamingComponentSeparatorLabel.Y = 0;
            this.templateConfigurationPropertiesNamingComponentSeparatorLabel.Data = "templateConfigurationPropertiesNamingComponentSeparatorLabel";
            this.templateConfigurationPropertiesNamingComponentSeparatorLabel.Text = "Component Separator";
            this.templateConfigurationPropertiesNamingComponentSeparatorLabel.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.templateConfigurationSnapshotNamingFrame.Add(this.templateConfigurationPropertiesNamingComponentSeparatorLabel);
            this.templateConfigurationPropertiesNamingComponentSeparatorValidateField.Width = 1;
            this.templateConfigurationPropertiesNamingComponentSeparatorValidateField.Height = 1;
            this.templateConfigurationPropertiesNamingComponentSeparatorValidateField.X = 26;
            this.templateConfigurationPropertiesNamingComponentSeparatorValidateField.Y = 0;
            this.templateConfigurationPropertiesNamingComponentSeparatorValidateField.ColorScheme = this.tgDefault;
            this.templateConfigurationPropertiesNamingComponentSeparatorValidateField.Provider = new Terminal.Gui.TextValidateProviders.TextRegexProvider("[0-9a-zA-Z:.+_-]{1}");
            this.templateConfigurationPropertiesNamingComponentSeparatorValidateField.Data = "templateConfigurationPropertiesNamingComponentSeparatorValidateField";
            this.templateConfigurationPropertiesNamingComponentSeparatorValidateField.Text = "";
            this.templateConfigurationPropertiesNamingComponentSeparatorValidateField.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.templateConfigurationSnapshotNamingFrame.Add(this.templateConfigurationPropertiesNamingComponentSeparatorValidateField);
            this.templateConfigurationPropertiesNamingPrefixLabel.Width = 3;
            this.templateConfigurationPropertiesNamingPrefixLabel.Height = 1;
            this.templateConfigurationPropertiesNamingPrefixLabel.X = 1;
            this.templateConfigurationPropertiesNamingPrefixLabel.Y = 1;
            this.templateConfigurationPropertiesNamingPrefixLabel.Data = "templateConfigurationPropertiesNamingPrefixLabel";
            this.templateConfigurationPropertiesNamingPrefixLabel.Text = "Prefix";
            this.templateConfigurationPropertiesNamingPrefixLabel.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.templateConfigurationSnapshotNamingFrame.Add(this.templateConfigurationPropertiesNamingPrefixLabel);
            this.templateConfigurationPropertiesNamingPrefixTextValidateField.Width = 12;
            this.templateConfigurationPropertiesNamingPrefixTextValidateField.Height = 1;
            this.templateConfigurationPropertiesNamingPrefixTextValidateField.X = 26;
            this.templateConfigurationPropertiesNamingPrefixTextValidateField.Y = 1;
            this.templateConfigurationPropertiesNamingPrefixTextValidateField.ColorScheme = this.tgDefault;
            this.templateConfigurationPropertiesNamingPrefixTextValidateField.Provider = new Terminal.Gui.TextValidateProviders.TextRegexProvider("^([0-9a-zA-Z]){1,12}$");
            this.templateConfigurationPropertiesNamingPrefixTextValidateField.Data = "templateConfigurationPropertiesNamingPrefixTextValidateField";
            this.templateConfigurationPropertiesNamingPrefixTextValidateField.Text = "";
            this.templateConfigurationPropertiesNamingPrefixTextValidateField.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.templateConfigurationSnapshotNamingFrame.Add(this.templateConfigurationPropertiesNamingPrefixTextValidateField);
            this.templateConfigurationPropertiesNamingTimestampFormatLabel.Width = 3;
            this.templateConfigurationPropertiesNamingTimestampFormatLabel.Height = 1;
            this.templateConfigurationPropertiesNamingTimestampFormatLabel.X = 1;
            this.templateConfigurationPropertiesNamingTimestampFormatLabel.Y = 2;
            this.templateConfigurationPropertiesNamingTimestampFormatLabel.Data = "templateConfigurationPropertiesNamingTimestampFormatLabel";
            this.templateConfigurationPropertiesNamingTimestampFormatLabel.Text = "Timestamp Format String";
            this.templateConfigurationPropertiesNamingTimestampFormatLabel.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.templateConfigurationSnapshotNamingFrame.Add(this.templateConfigurationPropertiesNamingTimestampFormatLabel);
            this.templateConfigurationPropertiesNamingTimestampFormatTextField.Width = 30;
            this.templateConfigurationPropertiesNamingTimestampFormatTextField.Height = 1;
            this.templateConfigurationPropertiesNamingTimestampFormatTextField.X = 26;
            this.templateConfigurationPropertiesNamingTimestampFormatTextField.Y = 2;
            this.templateConfigurationPropertiesNamingTimestampFormatTextField.ColorScheme = this.tgDefault;
            this.templateConfigurationPropertiesNamingTimestampFormatTextField.Secret = false;
            this.templateConfigurationPropertiesNamingTimestampFormatTextField.Data = "templateConfigurationPropertiesNamingTimestampFormatTextField";
            this.templateConfigurationPropertiesNamingTimestampFormatTextField.Text = "";
            this.templateConfigurationPropertiesNamingTimestampFormatTextField.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.templateConfigurationSnapshotNamingFrame.Add(this.templateConfigurationPropertiesNamingTimestampFormatTextField);
            this.templateConfigurationPropertiesNamingFrequentSuffixLabel.Width = 4;
            this.templateConfigurationPropertiesNamingFrequentSuffixLabel.Height = 1;
            this.templateConfigurationPropertiesNamingFrequentSuffixLabel.X = 1;
            this.templateConfigurationPropertiesNamingFrequentSuffixLabel.Y = 3;
            this.templateConfigurationPropertiesNamingFrequentSuffixLabel.Data = "templateConfigurationPropertiesNamingFrequentSuffixLabel";
            this.templateConfigurationPropertiesNamingFrequentSuffixLabel.Text = "Frequent Suffix";
            this.templateConfigurationPropertiesNamingFrequentSuffixLabel.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.templateConfigurationSnapshotNamingFrame.Add(this.templateConfigurationPropertiesNamingFrequentSuffixLabel);
            this.templateConfigurationPropertiesNamingFrequentSuffixTextValidateField.Width = 12;
            this.templateConfigurationPropertiesNamingFrequentSuffixTextValidateField.Height = 1;
            this.templateConfigurationPropertiesNamingFrequentSuffixTextValidateField.X = 26;
            this.templateConfigurationPropertiesNamingFrequentSuffixTextValidateField.Y = 3;
            this.templateConfigurationPropertiesNamingFrequentSuffixTextValidateField.ColorScheme = this.tgDefault;
            this.templateConfigurationPropertiesNamingFrequentSuffixTextValidateField.Provider = new Terminal.Gui.TextValidateProviders.TextRegexProvider("^[0-9a-zA-Z]{1,12}$");
            this.templateConfigurationPropertiesNamingFrequentSuffixTextValidateField.Data = "templateConfigurationPropertiesNamingFrequentSuffixTextValidateField";
            this.templateConfigurationPropertiesNamingFrequentSuffixTextValidateField.Text = "";
            this.templateConfigurationPropertiesNamingFrequentSuffixTextValidateField.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.templateConfigurationSnapshotNamingFrame.Add(this.templateConfigurationPropertiesNamingFrequentSuffixTextValidateField);
            this.templateConfigurationPropertiesNamingHourlySuffixLabel.Width = 4;
            this.templateConfigurationPropertiesNamingHourlySuffixLabel.Height = 1;
            this.templateConfigurationPropertiesNamingHourlySuffixLabel.X = 1;
            this.templateConfigurationPropertiesNamingHourlySuffixLabel.Y = 4;
            this.templateConfigurationPropertiesNamingHourlySuffixLabel.Data = "templateConfigurationPropertiesNamingHourlySuffixLabel";
            this.templateConfigurationPropertiesNamingHourlySuffixLabel.Text = "Hourly Suffix";
            this.templateConfigurationPropertiesNamingHourlySuffixLabel.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.templateConfigurationSnapshotNamingFrame.Add(this.templateConfigurationPropertiesNamingHourlySuffixLabel);
            this.templateConfigurationPropertiesNamingHourlySuffixTextValidateField.Width = 12;
            this.templateConfigurationPropertiesNamingHourlySuffixTextValidateField.Height = 1;
            this.templateConfigurationPropertiesNamingHourlySuffixTextValidateField.X = 26;
            this.templateConfigurationPropertiesNamingHourlySuffixTextValidateField.Y = 4;
            this.templateConfigurationPropertiesNamingHourlySuffixTextValidateField.ColorScheme = this.tgDefault;
            this.templateConfigurationPropertiesNamingHourlySuffixTextValidateField.Provider = new Terminal.Gui.TextValidateProviders.TextRegexProvider("[0-9a-zA-Z]{1,12}");
            this.templateConfigurationPropertiesNamingHourlySuffixTextValidateField.Data = "templateConfigurationPropertiesNamingHourlySuffixTextValidateField";
            this.templateConfigurationPropertiesNamingHourlySuffixTextValidateField.Text = "";
            this.templateConfigurationPropertiesNamingHourlySuffixTextValidateField.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.templateConfigurationSnapshotNamingFrame.Add(this.templateConfigurationPropertiesNamingHourlySuffixTextValidateField);
            this.templateConfigurationPropertiesNamingDailySuffixLabel.Width = 4;
            this.templateConfigurationPropertiesNamingDailySuffixLabel.Height = 1;
            this.templateConfigurationPropertiesNamingDailySuffixLabel.X = 1;
            this.templateConfigurationPropertiesNamingDailySuffixLabel.Y = 5;
            this.templateConfigurationPropertiesNamingDailySuffixLabel.Data = "templateConfigurationPropertiesNamingDailySuffixLabel";
            this.templateConfigurationPropertiesNamingDailySuffixLabel.Text = "Daily Suffix";
            this.templateConfigurationPropertiesNamingDailySuffixLabel.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.templateConfigurationSnapshotNamingFrame.Add(this.templateConfigurationPropertiesNamingDailySuffixLabel);
            this.templateConfigurationPropertiesNamingDailySuffixTextValidateField.Width = 12;
            this.templateConfigurationPropertiesNamingDailySuffixTextValidateField.Height = 1;
            this.templateConfigurationPropertiesNamingDailySuffixTextValidateField.X = 26;
            this.templateConfigurationPropertiesNamingDailySuffixTextValidateField.Y = 5;
            this.templateConfigurationPropertiesNamingDailySuffixTextValidateField.ColorScheme = this.tgDefault;
            this.templateConfigurationPropertiesNamingDailySuffixTextValidateField.Provider = new Terminal.Gui.TextValidateProviders.TextRegexProvider("[0-9a-zA-Z]{1,12}");
            this.templateConfigurationPropertiesNamingDailySuffixTextValidateField.Data = "templateConfigurationPropertiesNamingDailySuffixTextValidateField";
            this.templateConfigurationPropertiesNamingDailySuffixTextValidateField.Text = "";
            this.templateConfigurationPropertiesNamingDailySuffixTextValidateField.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.templateConfigurationSnapshotNamingFrame.Add(this.templateConfigurationPropertiesNamingDailySuffixTextValidateField);
            this.templateConfigurationPropertiesNamingWeeklySuffixLabel.Width = 4;
            this.templateConfigurationPropertiesNamingWeeklySuffixLabel.Height = 1;
            this.templateConfigurationPropertiesNamingWeeklySuffixLabel.X = 1;
            this.templateConfigurationPropertiesNamingWeeklySuffixLabel.Y = 6;
            this.templateConfigurationPropertiesNamingWeeklySuffixLabel.Data = "templateConfigurationPropertiesNamingWeeklySuffixLabel";
            this.templateConfigurationPropertiesNamingWeeklySuffixLabel.Text = "Weekly Suffix";
            this.templateConfigurationPropertiesNamingWeeklySuffixLabel.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.templateConfigurationSnapshotNamingFrame.Add(this.templateConfigurationPropertiesNamingWeeklySuffixLabel);
            this.templateConfigurationPropertiesNamingWeeklySuffixTextValidateField.Width = 12;
            this.templateConfigurationPropertiesNamingWeeklySuffixTextValidateField.Height = 1;
            this.templateConfigurationPropertiesNamingWeeklySuffixTextValidateField.X = 26;
            this.templateConfigurationPropertiesNamingWeeklySuffixTextValidateField.Y = 6;
            this.templateConfigurationPropertiesNamingWeeklySuffixTextValidateField.ColorScheme = this.tgDefault;
            this.templateConfigurationPropertiesNamingWeeklySuffixTextValidateField.Provider = new Terminal.Gui.TextValidateProviders.TextRegexProvider("[0-9a-zA-Z]{1,12}");
            this.templateConfigurationPropertiesNamingWeeklySuffixTextValidateField.Data = "templateConfigurationPropertiesNamingWeeklySuffixTextValidateField";
            this.templateConfigurationPropertiesNamingWeeklySuffixTextValidateField.Text = "";
            this.templateConfigurationPropertiesNamingWeeklySuffixTextValidateField.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.templateConfigurationSnapshotNamingFrame.Add(this.templateConfigurationPropertiesNamingWeeklySuffixTextValidateField);
            this.templateConfigurationPropertiesNamingMonthlySuffixLabel.Width = 4;
            this.templateConfigurationPropertiesNamingMonthlySuffixLabel.Height = 1;
            this.templateConfigurationPropertiesNamingMonthlySuffixLabel.X = 1;
            this.templateConfigurationPropertiesNamingMonthlySuffixLabel.Y = 7;
            this.templateConfigurationPropertiesNamingMonthlySuffixLabel.Data = "templateConfigurationPropertiesNamingMonthlySuffixLabel";
            this.templateConfigurationPropertiesNamingMonthlySuffixLabel.Text = "Monthly Suffix";
            this.templateConfigurationPropertiesNamingMonthlySuffixLabel.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.templateConfigurationSnapshotNamingFrame.Add(this.templateConfigurationPropertiesNamingMonthlySuffixLabel);
            this.templateConfigurationPropertiesNamingMonthlySuffixTextValidateField.Width = 12;
            this.templateConfigurationPropertiesNamingMonthlySuffixTextValidateField.Height = 1;
            this.templateConfigurationPropertiesNamingMonthlySuffixTextValidateField.X = 26;
            this.templateConfigurationPropertiesNamingMonthlySuffixTextValidateField.Y = 7;
            this.templateConfigurationPropertiesNamingMonthlySuffixTextValidateField.ColorScheme = this.tgDefault;
            this.templateConfigurationPropertiesNamingMonthlySuffixTextValidateField.Provider = new Terminal.Gui.TextValidateProviders.TextRegexProvider("[0-9a-zA-Z]{1,12}");
            this.templateConfigurationPropertiesNamingMonthlySuffixTextValidateField.Data = "templateConfigurationPropertiesNamingMonthlySuffixTextValidateField";
            this.templateConfigurationPropertiesNamingMonthlySuffixTextValidateField.Text = "";
            this.templateConfigurationPropertiesNamingMonthlySuffixTextValidateField.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.templateConfigurationSnapshotNamingFrame.Add(this.templateConfigurationPropertiesNamingMonthlySuffixTextValidateField);
            this.templateConfigurationPropertiesNamingYearlySuffixLabel.Width = 4;
            this.templateConfigurationPropertiesNamingYearlySuffixLabel.Height = 1;
            this.templateConfigurationPropertiesNamingYearlySuffixLabel.X = 1;
            this.templateConfigurationPropertiesNamingYearlySuffixLabel.Y = 8;
            this.templateConfigurationPropertiesNamingYearlySuffixLabel.Data = "templateConfigurationPropertiesNamingYearlySuffixLabel";
            this.templateConfigurationPropertiesNamingYearlySuffixLabel.Text = "Yearly Suffix";
            this.templateConfigurationPropertiesNamingYearlySuffixLabel.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.templateConfigurationSnapshotNamingFrame.Add(this.templateConfigurationPropertiesNamingYearlySuffixLabel);
            this.templateConfigurationPropertiesNamingYearlySuffixTextValidateField.Width = 12;
            this.templateConfigurationPropertiesNamingYearlySuffixTextValidateField.Height = 1;
            this.templateConfigurationPropertiesNamingYearlySuffixTextValidateField.X = 26;
            this.templateConfigurationPropertiesNamingYearlySuffixTextValidateField.Y = 8;
            this.templateConfigurationPropertiesNamingYearlySuffixTextValidateField.ColorScheme = this.tgDefault;
            this.templateConfigurationPropertiesNamingYearlySuffixTextValidateField.Provider = new Terminal.Gui.TextValidateProviders.TextRegexProvider("[0-9a-zA-Z]{1,12}");
            this.templateConfigurationPropertiesNamingYearlySuffixTextValidateField.Data = "templateConfigurationPropertiesNamingYearlySuffixTextValidateField";
            this.templateConfigurationPropertiesNamingYearlySuffixTextValidateField.Text = "";
            this.templateConfigurationPropertiesNamingYearlySuffixTextValidateField.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.templateConfigurationSnapshotNamingFrame.Add(this.templateConfigurationPropertiesNamingYearlySuffixTextValidateField);
            this.templateConfigurationPropertiesSnapshotTimingFrame.Width = 59;
            this.templateConfigurationPropertiesSnapshotTimingFrame.Height = Dim.Fill(1);
            this.templateConfigurationPropertiesSnapshotTimingFrame.X = 0;
            this.templateConfigurationPropertiesSnapshotTimingFrame.Y = Pos.Bottom(templateConfigurationSnapshotNamingFrame);
            this.templateConfigurationPropertiesSnapshotTimingFrame.Data = "templateConfigurationPropertiesSnapshotTimingFrame";
            this.templateConfigurationPropertiesSnapshotTimingFrame.Border.BorderStyle = Terminal.Gui.BorderStyle.Single;
            this.templateConfigurationPropertiesSnapshotTimingFrame.Border.BorderBrush = Terminal.Gui.Color.White;
            this.templateConfigurationPropertiesSnapshotTimingFrame.Border.Effect3D = false;
            this.templateConfigurationPropertiesSnapshotTimingFrame.Border.Effect3DBrush = null;
            this.templateConfigurationPropertiesSnapshotTimingFrame.Border.DrawMarginFrame = true;
            this.templateConfigurationPropertiesSnapshotTimingFrame.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.templateConfigurationPropertiesSnapshotTimingFrame.Title = "Snapshot Timing";
            this.templateConfigurationTemplatePropertiesFrame.Add(this.templateConfigurationPropertiesSnapshotTimingFrame);
            this.stemplateConfigurationPropertiesTimingFrequentPeriodLabel.Width = 4;
            this.stemplateConfigurationPropertiesTimingFrequentPeriodLabel.Height = 1;
            this.stemplateConfigurationPropertiesTimingFrequentPeriodLabel.X = 0;
            this.stemplateConfigurationPropertiesTimingFrequentPeriodLabel.Y = 0;
            this.stemplateConfigurationPropertiesTimingFrequentPeriodLabel.Data = "stemplateConfigurationPropertiesTimingFrequentPeriodLabel";
            this.stemplateConfigurationPropertiesTimingFrequentPeriodLabel.Text = "Frequent Perio";
            this.stemplateConfigurationPropertiesTimingFrequentPeriodLabel.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.templateConfigurationPropertiesSnapshotTimingFrame.Add(this.stemplateConfigurationPropertiesTimingFrequentPeriodLabel);
            this.templateConfigurationPropertiesTimingFrequentPeriodRadioGroup.Width = 25;
            this.templateConfigurationPropertiesTimingFrequentPeriodRadioGroup.Height = 1;
            this.templateConfigurationPropertiesTimingFrequentPeriodRadioGroup.X = 18;
            this.templateConfigurationPropertiesTimingFrequentPeriodRadioGroup.Y = 0;
            this.templateConfigurationPropertiesTimingFrequentPeriodRadioGroup.ColorScheme = this.tgDefault;
            this.templateConfigurationPropertiesTimingFrequentPeriodRadioGroup.Data = "templateConfigurationPropertiesTimingFrequentPeriodRadioGroup";
            this.templateConfigurationPropertiesTimingFrequentPeriodRadioGroup.Text = "";
            this.templateConfigurationPropertiesTimingFrequentPeriodRadioGroup.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.templateConfigurationPropertiesTimingFrequentPeriodRadioGroup.RadioLabels = new NStack.ustring[] {
                    "5",
                    "10",
                    "15",
                    "20",
                    "30"};
            this.templateConfigurationPropertiesTimingFrequentPeriodRadioGroup.DisplayMode = Terminal.Gui.DisplayModeLayout.Horizontal;
            this.templateConfigurationPropertiesSnapshotTimingFrame.Add(this.templateConfigurationPropertiesTimingFrequentPeriodRadioGroup);
            this.templateConfigurationPropertiesTimingHourlyLabel.Width = 6;
            this.templateConfigurationPropertiesTimingHourlyLabel.Height = 1;
            this.templateConfigurationPropertiesTimingHourlyLabel.X = 0;
            this.templateConfigurationPropertiesTimingHourlyLabel.Y = 1;
            this.templateConfigurationPropertiesTimingHourlyLabel.Data = "templateConfigurationPropertiesTimingHourlyLabel";
            this.templateConfigurationPropertiesTimingHourlyLabel.Text = "Hourly";
            this.templateConfigurationPropertiesTimingHourlyLabel.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.templateConfigurationPropertiesSnapshotTimingFrame.Add(this.templateConfigurationPropertiesTimingHourlyLabel);
            this.templateConfigurationPropertiesTimingHourlyMinuteLabel.Width = 4;
            this.templateConfigurationPropertiesTimingHourlyMinuteLabel.Height = 1;
            this.templateConfigurationPropertiesTimingHourlyMinuteLabel.X = 2;
            this.templateConfigurationPropertiesTimingHourlyMinuteLabel.Y = 2;
            this.templateConfigurationPropertiesTimingHourlyMinuteLabel.Data = "templateConfigurationPropertiesTimingHourlyMinuteLabel";
            this.templateConfigurationPropertiesTimingHourlyMinuteLabel.Text = "Minute";
            this.templateConfigurationPropertiesTimingHourlyMinuteLabel.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.templateConfigurationPropertiesSnapshotTimingFrame.Add(this.templateConfigurationPropertiesTimingHourlyMinuteLabel);
            this.hourlyMinuteTextValidateField.Width = 4;
            this.hourlyMinuteTextValidateField.Height = 1;
            this.hourlyMinuteTextValidateField.X = 9;
            this.hourlyMinuteTextValidateField.Y = 2;
            this.hourlyMinuteTextValidateField.ColorScheme = this.tgDefault;
            this.hourlyMinuteTextValidateField.Provider = new Terminal.Gui.TextValidateProviders.TextRegexProvider("^[0-5]?[0-9]$");
            this.hourlyMinuteTextValidateField.Data = "templateConfigurationPropertiesTimingHourlyMinuteTextValidateField";
            this.hourlyMinuteTextValidateField.Text = "";
            this.hourlyMinuteTextValidateField.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.templateConfigurationPropertiesSnapshotTimingFrame.Add(this.hourlyMinuteTextValidateField);
            this.comboBox.Width = 13;
            this.comboBox.Height = 1;
            this.comboBox.X = 29;
            this.comboBox.Y = 2;
            this.comboBox.ColorScheme = this.tgDefault;
            this.comboBox.Data = "comboBox";
            this.comboBox.Text = "";
            this.comboBox.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.templateConfigurationPropertiesSnapshotTimingFrame.Add(this.comboBox);
            this.templateConfigurationPropertiesTimingDailyLabel.Width = 4;
            this.templateConfigurationPropertiesTimingDailyLabel.Height = 1;
            this.templateConfigurationPropertiesTimingDailyLabel.X = 0;
            this.templateConfigurationPropertiesTimingDailyLabel.Y = 3;
            this.templateConfigurationPropertiesTimingDailyLabel.Data = "templateConfigurationPropertiesTimingDailyLabel";
            this.templateConfigurationPropertiesTimingDailyLabel.Text = "Daily";
            this.templateConfigurationPropertiesTimingDailyLabel.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.templateConfigurationPropertiesSnapshotTimingFrame.Add(this.templateConfigurationPropertiesTimingDailyLabel);
            this.templateConfigurationPropertiesDailyTimeLabel.Width = 4;
            this.templateConfigurationPropertiesDailyTimeLabel.Height = 1;
            this.templateConfigurationPropertiesDailyTimeLabel.X = 2;
            this.templateConfigurationPropertiesDailyTimeLabel.Y = 4;
            this.templateConfigurationPropertiesDailyTimeLabel.Data = "templateConfigurationPropertiesDailyTimeLabel";
            this.templateConfigurationPropertiesDailyTimeLabel.Text = "Time";
            this.templateConfigurationPropertiesDailyTimeLabel.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.templateConfigurationPropertiesSnapshotTimingFrame.Add(this.templateConfigurationPropertiesDailyTimeLabel);
            this.dailyTimeTimeField.Width = 10;
            this.dailyTimeTimeField.Height = 1;
            this.dailyTimeTimeField.X = 9;
            this.dailyTimeTimeField.Y = 4;
            this.dailyTimeTimeField.ColorScheme = this.tgDefault;
            this.dailyTimeTimeField.Secret = false;
            this.dailyTimeTimeField.Data = "dailyTimeTimeField";
            this.dailyTimeTimeField.Text = "00:00:00";
            this.dailyTimeTimeField.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.templateConfigurationPropertiesSnapshotTimingFrame.Add(this.dailyTimeTimeField);
            this.templateConfigurationPropertiesWeeklyLabel.Width = 5;
            this.templateConfigurationPropertiesWeeklyLabel.Height = 1;
            this.templateConfigurationPropertiesWeeklyLabel.X = 0;
            this.templateConfigurationPropertiesWeeklyLabel.Y = 5;
            this.templateConfigurationPropertiesWeeklyLabel.Data = "templateConfigurationPropertiesWeeklyLabel";
            this.templateConfigurationPropertiesWeeklyLabel.Text = "Weekly";
            this.templateConfigurationPropertiesWeeklyLabel.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.templateConfigurationPropertiesSnapshotTimingFrame.Add(this.templateConfigurationPropertiesWeeklyLabel);
            this.templateConfigurationPropertiesWeeklyLabel2.Width = 5;
            this.templateConfigurationPropertiesWeeklyLabel2.Height = 1;
            this.templateConfigurationPropertiesWeeklyLabel2.X = 2;
            this.templateConfigurationPropertiesWeeklyLabel2.Y = 6;
            this.templateConfigurationPropertiesWeeklyLabel2.Data = "templateConfigurationPropertiesWeeklyLabel2";
            this.templateConfigurationPropertiesWeeklyLabel2.Text = "Day";
            this.templateConfigurationPropertiesWeeklyLabel2.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.templateConfigurationPropertiesSnapshotTimingFrame.Add(this.templateConfigurationPropertiesWeeklyLabel2);
            this.templateConfigurationPropertiesTimingWeeklyDayTextValidateField.Width = 10;
            this.templateConfigurationPropertiesTimingWeeklyDayTextValidateField.Height = 1;
            this.templateConfigurationPropertiesTimingWeeklyDayTextValidateField.X = 9;
            this.templateConfigurationPropertiesTimingWeeklyDayTextValidateField.Y = 6;
            this.templateConfigurationPropertiesTimingWeeklyDayTextValidateField.ColorScheme = this.tgDefault;
            this.templateConfigurationPropertiesTimingWeeklyDayTextValidateField.Provider = new Terminal.Gui.TextValidateProviders.TextRegexProvider("^\\w+$");
            this.templateConfigurationPropertiesTimingWeeklyDayTextValidateField.Data = "templateConfigurationPropertiesTimingWeeklyDayTextValidateField";
            this.templateConfigurationPropertiesTimingWeeklyDayTextValidateField.Text = "";
            this.templateConfigurationPropertiesTimingWeeklyDayTextValidateField.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.templateConfigurationPropertiesSnapshotTimingFrame.Add(this.templateConfigurationPropertiesTimingWeeklyDayTextValidateField);
            this.templateConfigurationPropertiesWeeklyTimeLabel.Width = 4;
            this.templateConfigurationPropertiesWeeklyTimeLabel.Height = 1;
            this.templateConfigurationPropertiesWeeklyTimeLabel.X = 24;
            this.templateConfigurationPropertiesWeeklyTimeLabel.Y = 6;
            this.templateConfigurationPropertiesWeeklyTimeLabel.Data = "templateConfigurationPropertiesWeeklyTimeLabel";
            this.templateConfigurationPropertiesWeeklyTimeLabel.Text = "Time";
            this.templateConfigurationPropertiesWeeklyTimeLabel.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.templateConfigurationPropertiesSnapshotTimingFrame.Add(this.templateConfigurationPropertiesWeeklyTimeLabel);
            this.weeklyTimeTimeField.Width = 10;
            this.weeklyTimeTimeField.Height = 1;
            this.weeklyTimeTimeField.X = 29;
            this.weeklyTimeTimeField.Y = 6;
            this.weeklyTimeTimeField.ColorScheme = this.tgDefault;
            this.weeklyTimeTimeField.Secret = false;
            this.weeklyTimeTimeField.Data = "weeklyTimeTimeField";
            this.weeklyTimeTimeField.Text = "00:00:00";
            this.weeklyTimeTimeField.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.templateConfigurationPropertiesSnapshotTimingFrame.Add(this.weeklyTimeTimeField);
            this.templateConfigurationPropertiesMonthlyLabel.Width = 10;
            this.templateConfigurationPropertiesMonthlyLabel.Height = 1;
            this.templateConfigurationPropertiesMonthlyLabel.X = 0;
            this.templateConfigurationPropertiesMonthlyLabel.Y = 7;
            this.templateConfigurationPropertiesMonthlyLabel.Data = "templateConfigurationPropertiesMonthlyLabel";
            this.templateConfigurationPropertiesMonthlyLabel.Text = "Monthly";
            this.templateConfigurationPropertiesMonthlyLabel.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.templateConfigurationPropertiesSnapshotTimingFrame.Add(this.templateConfigurationPropertiesMonthlyLabel);
            this.templateConfigurationPropertiesMonthlyDayLabel.Width = 4;
            this.templateConfigurationPropertiesMonthlyDayLabel.Height = 1;
            this.templateConfigurationPropertiesMonthlyDayLabel.X = 2;
            this.templateConfigurationPropertiesMonthlyDayLabel.Y = 8;
            this.templateConfigurationPropertiesMonthlyDayLabel.Data = "templateConfigurationPropertiesMonthlyDayLabel";
            this.templateConfigurationPropertiesMonthlyDayLabel.Text = "Day";
            this.templateConfigurationPropertiesMonthlyDayLabel.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.templateConfigurationPropertiesSnapshotTimingFrame.Add(this.templateConfigurationPropertiesMonthlyDayLabel);
            this.templateConfigurationPropertiesTimingMonthlyDayTextValidateField.Width = 4;
            this.templateConfigurationPropertiesTimingMonthlyDayTextValidateField.Height = 1;
            this.templateConfigurationPropertiesTimingMonthlyDayTextValidateField.X = 9;
            this.templateConfigurationPropertiesTimingMonthlyDayTextValidateField.Y = 8;
            this.templateConfigurationPropertiesTimingMonthlyDayTextValidateField.ColorScheme = this.tgDefault;
            this.templateConfigurationPropertiesTimingMonthlyDayTextValidateField.Provider = new Terminal.Gui.TextValidateProviders.TextRegexProvider("^\\d\\d$");
            this.templateConfigurationPropertiesTimingMonthlyDayTextValidateField.Data = "templateConfigurationPropertiesTimingMonthlyDayTextValidateField";
            this.templateConfigurationPropertiesTimingMonthlyDayTextValidateField.Text = "";
            this.templateConfigurationPropertiesTimingMonthlyDayTextValidateField.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.templateConfigurationPropertiesSnapshotTimingFrame.Add(this.templateConfigurationPropertiesTimingMonthlyDayTextValidateField);
            this.templateConfigurationPropertiesMonthlyTimeLabel.Width = 4;
            this.templateConfigurationPropertiesMonthlyTimeLabel.Height = 1;
            this.templateConfigurationPropertiesMonthlyTimeLabel.X = 24;
            this.templateConfigurationPropertiesMonthlyTimeLabel.Y = 8;
            this.templateConfigurationPropertiesMonthlyTimeLabel.Data = "templateConfigurationPropertiesMonthlyTimeLabel";
            this.templateConfigurationPropertiesMonthlyTimeLabel.Text = "Time";
            this.templateConfigurationPropertiesMonthlyTimeLabel.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.templateConfigurationPropertiesSnapshotTimingFrame.Add(this.templateConfigurationPropertiesMonthlyTimeLabel);
            this.monthlyTimeTimeField.Width = 10;
            this.monthlyTimeTimeField.Height = 1;
            this.monthlyTimeTimeField.X = 29;
            this.monthlyTimeTimeField.Y = 8;
            this.monthlyTimeTimeField.ColorScheme = this.tgDefault;
            this.monthlyTimeTimeField.Secret = false;
            this.monthlyTimeTimeField.Data = "monthlyTimeTimeField";
            this.monthlyTimeTimeField.Text = "00:00:00";
            this.monthlyTimeTimeField.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.templateConfigurationPropertiesSnapshotTimingFrame.Add(this.monthlyTimeTimeField);
            this.templateConfigurationPropertiesTimingYearlyLabel.Width = 6;
            this.templateConfigurationPropertiesTimingYearlyLabel.Height = 1;
            this.templateConfigurationPropertiesTimingYearlyLabel.X = 0;
            this.templateConfigurationPropertiesTimingYearlyLabel.Y = 9;
            this.templateConfigurationPropertiesTimingYearlyLabel.Data = "templateConfigurationPropertiesTimingYearlyLabel";
            this.templateConfigurationPropertiesTimingYearlyLabel.Text = "Yearly";
            this.templateConfigurationPropertiesTimingYearlyLabel.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.templateConfigurationPropertiesSnapshotTimingFrame.Add(this.templateConfigurationPropertiesTimingYearlyLabel);
            this.templateConfigurationPropertiesYearlyMonthLabel.Width = 4;
            this.templateConfigurationPropertiesYearlyMonthLabel.Height = 1;
            this.templateConfigurationPropertiesYearlyMonthLabel.X = 2;
            this.templateConfigurationPropertiesYearlyMonthLabel.Y = 10;
            this.templateConfigurationPropertiesYearlyMonthLabel.Data = "templateConfigurationPropertiesYearlyMonthLabel";
            this.templateConfigurationPropertiesYearlyMonthLabel.Text = "Month";
            this.templateConfigurationPropertiesYearlyMonthLabel.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.templateConfigurationPropertiesSnapshotTimingFrame.Add(this.templateConfigurationPropertiesYearlyMonthLabel);
            this.templateConfigurationPropertiesTimingYearlyMonthTextValidateField.Width = 10;
            this.templateConfigurationPropertiesTimingYearlyMonthTextValidateField.Height = 1;
            this.templateConfigurationPropertiesTimingYearlyMonthTextValidateField.X = 9;
            this.templateConfigurationPropertiesTimingYearlyMonthTextValidateField.Y = 10;
            this.templateConfigurationPropertiesTimingYearlyMonthTextValidateField.ColorScheme = this.tgDefault;
            this.templateConfigurationPropertiesTimingYearlyMonthTextValidateField.Provider = new Terminal.Gui.TextValidateProviders.TextRegexProvider("^\\w+$");
            this.templateConfigurationPropertiesTimingYearlyMonthTextValidateField.Data = "templateConfigurationPropertiesTimingYearlyMonthTextValidateField";
            this.templateConfigurationPropertiesTimingYearlyMonthTextValidateField.Text = "";
            this.templateConfigurationPropertiesTimingYearlyMonthTextValidateField.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.templateConfigurationPropertiesSnapshotTimingFrame.Add(this.templateConfigurationPropertiesTimingYearlyMonthTextValidateField);
            this.templateConfigurationPropertiesYearlyDayLabel.Width = 2;
            this.templateConfigurationPropertiesYearlyDayLabel.Height = 1;
            this.templateConfigurationPropertiesYearlyDayLabel.X = 24;
            this.templateConfigurationPropertiesYearlyDayLabel.Y = 10;
            this.templateConfigurationPropertiesYearlyDayLabel.Data = "templateConfigurationPropertiesYearlyDayLabel";
            this.templateConfigurationPropertiesYearlyDayLabel.Text = "Day";
            this.templateConfigurationPropertiesYearlyDayLabel.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.templateConfigurationPropertiesSnapshotTimingFrame.Add(this.templateConfigurationPropertiesYearlyDayLabel);
            this.templateConfigurationPropertiesTimingYearlyDayTextValidateField.Width = 4;
            this.templateConfigurationPropertiesTimingYearlyDayTextValidateField.Height = 1;
            this.templateConfigurationPropertiesTimingYearlyDayTextValidateField.X = 29;
            this.templateConfigurationPropertiesTimingYearlyDayTextValidateField.Y = 10;
            this.templateConfigurationPropertiesTimingYearlyDayTextValidateField.ColorScheme = this.tgDefault;
            this.templateConfigurationPropertiesTimingYearlyDayTextValidateField.Provider = new Terminal.Gui.TextValidateProviders.TextRegexProvider("^\\d?\\d$");
            this.templateConfigurationPropertiesTimingYearlyDayTextValidateField.Data = "templateConfigurationPropertiesTimingYearlyDayTextValidateField";
            this.templateConfigurationPropertiesTimingYearlyDayTextValidateField.Text = "";
            this.templateConfigurationPropertiesTimingYearlyDayTextValidateField.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.templateConfigurationPropertiesSnapshotTimingFrame.Add(this.templateConfigurationPropertiesTimingYearlyDayTextValidateField);
            this.templateConfigurationPropertiesYearlyTimeLabel.Width = 3;
            this.templateConfigurationPropertiesYearlyTimeLabel.Height = 1;
            this.templateConfigurationPropertiesYearlyTimeLabel.X = 41;
            this.templateConfigurationPropertiesYearlyTimeLabel.Y = 10;
            this.templateConfigurationPropertiesYearlyTimeLabel.Data = "templateConfigurationPropertiesYearlyTimeLabel";
            this.templateConfigurationPropertiesYearlyTimeLabel.Text = "Time";
            this.templateConfigurationPropertiesYearlyTimeLabel.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.templateConfigurationPropertiesSnapshotTimingFrame.Add(this.templateConfigurationPropertiesYearlyTimeLabel);
            this.yearlyTimeTimeField.Width = 10;
            this.yearlyTimeTimeField.Height = 1;
            this.yearlyTimeTimeField.X = 46;
            this.yearlyTimeTimeField.Y = 10;
            this.yearlyTimeTimeField.ColorScheme = this.tgDefault;
            this.yearlyTimeTimeField.Secret = false;
            this.yearlyTimeTimeField.Data = "yearlyTimeTimeField";
            this.yearlyTimeTimeField.Text = "00:00:00";
            this.yearlyTimeTimeField.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.templateConfigurationPropertiesSnapshotTimingFrame.Add(this.yearlyTimeTimeField);
            this.applyCurrentButton.Width = 9;
            this.applyCurrentButton.Height = 1;
            this.applyCurrentButton.X = 19;
            this.applyCurrentButton.Y = 25;
            this.applyCurrentButton.ColorScheme = this.tgDefault;
            this.applyCurrentButton.Data = "applyCurrentButton";
            this.applyCurrentButton.Text = "Apply";
            this.applyCurrentButton.TextAlignment = Terminal.Gui.TextAlignment.Centered;
            this.applyCurrentButton.IsDefault = false;
            this.templateConfigurationTemplatePropertiesFrame.Add(this.applyCurrentButton);
            this.templateConfigurationResetCurrentButton.Width = 9;
            this.templateConfigurationResetCurrentButton.Height = 1;
            this.templateConfigurationResetCurrentButton.X = 31;
            this.templateConfigurationResetCurrentButton.Y = 25;
            this.templateConfigurationResetCurrentButton.ColorScheme = this.tgDefault;
            this.templateConfigurationResetCurrentButton.Data = "templateConfigurationResetCurrentButton";
            this.templateConfigurationResetCurrentButton.Text = "Reset";
            this.templateConfigurationResetCurrentButton.TextAlignment = Terminal.Gui.TextAlignment.Centered;
            this.templateConfigurationResetCurrentButton.IsDefault = false;
            this.templateConfigurationTemplatePropertiesFrame.Add(this.templateConfigurationResetCurrentButton);
            this.templateConfigurationTemplateListFrame.Width = 42;
            this.templateConfigurationTemplateListFrame.Height = 16;
            this.templateConfigurationTemplateListFrame.X = 0;
            this.templateConfigurationTemplateListFrame.Y = Pos.Center();
            this.templateConfigurationTemplateListFrame.Data = "templateConfigurationTemplateListFrame";
            this.templateConfigurationTemplateListFrame.Border.BorderStyle = Terminal.Gui.BorderStyle.Single;
            this.templateConfigurationTemplateListFrame.Border.BorderBrush = Terminal.Gui.Color.White;
            this.templateConfigurationTemplateListFrame.Border.Effect3D = false;
            this.templateConfigurationTemplateListFrame.Border.Effect3DBrush = null;
            this.templateConfigurationTemplateListFrame.Border.DrawMarginFrame = true;
            this.templateConfigurationTemplateListFrame.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.templateConfigurationTemplateListFrame.Title = "Templates";
            this.Add(this.templateConfigurationTemplateListFrame);
            this.templateConfigurationTemplateListView.Width = Dim.Fill(0);
            this.templateConfigurationTemplateListView.Height = Dim.Fill(0);
            this.templateConfigurationTemplateListView.X = 0;
            this.templateConfigurationTemplateListView.Y = 0;
            this.templateConfigurationTemplateListView.ColorScheme = this.tgDefault;
            this.templateConfigurationTemplateListView.Data = "templateConfigurationTemplateListView";
            this.templateConfigurationTemplateListView.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.templateConfigurationTemplateListView.Source = new Terminal.Gui.ListWrapper(new string[0]);
            this.templateConfigurationTemplateListView.AllowsMarking = false;
            this.templateConfigurationTemplateListView.AllowsMultipleSelection = false;
            this.templateConfigurationTemplateListFrame.Add(this.templateConfigurationTemplateListView);
            this.newTemplateNameTextValidateField.Width = 25;
            this.newTemplateNameTextValidateField.Height = 1;
            this.newTemplateNameTextValidateField.X = 8;
            this.newTemplateNameTextValidateField.Y = 22;
            this.newTemplateNameTextValidateField.ColorScheme = this.tgDefault;
            this.newTemplateNameTextValidateField.Provider = new Terminal.Gui.TextValidateProviders.TextRegexProvider("^[a-zA-Z0-9][a-zA-Z0-9 _-]{0,24}$");
            this.newTemplateNameTextValidateField.Data = "newTemplateNameTextValidateField";
            this.newTemplateNameTextValidateField.Text = "New Template Name";
            this.newTemplateNameTextValidateField.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.Add(this.newTemplateNameTextValidateField);
            this.addTemplateButton.Width = 11;
            this.addTemplateButton.Height = 1;
            this.addTemplateButton.X = 8;
            this.addTemplateButton.Y = 24;
            this.addTemplateButton.ColorScheme = this.tgDefault;
            this.addTemplateButton.Data = "addTemplateButton";
            this.addTemplateButton.Text = "Add New";
            this.addTemplateButton.TextAlignment = Terminal.Gui.TextAlignment.Centered;
            this.addTemplateButton.IsDefault = false;
            this.Add(this.addTemplateButton);
            this.templateConfigurationDeleteTemplateButton.Width = 10;
            this.templateConfigurationDeleteTemplateButton.Height = 1;
            this.templateConfigurationDeleteTemplateButton.X = 23;
            this.templateConfigurationDeleteTemplateButton.Y = 24;
            this.templateConfigurationDeleteTemplateButton.ColorScheme = this.tgDefault;
            this.templateConfigurationDeleteTemplateButton.Data = "templateConfigurationDeleteTemplateButton";
            this.templateConfigurationDeleteTemplateButton.Text = "Delete";
            this.templateConfigurationDeleteTemplateButton.TextAlignment = Terminal.Gui.TextAlignment.Centered;
            this.templateConfigurationDeleteTemplateButton.IsDefault = false;
            this.Add(this.templateConfigurationDeleteTemplateButton);
            this.templateConfigurationSaveAllButton.Width = 12;
            this.templateConfigurationSaveAllButton.Height = 1;
            this.templateConfigurationSaveAllButton.X = 14;
            this.templateConfigurationSaveAllButton.Y = 26;
            this.templateConfigurationSaveAllButton.ColorScheme = this.tgDefault;
            this.templateConfigurationSaveAllButton.Data = "templateConfigurationSaveAllButton";
            this.templateConfigurationSaveAllButton.Text = "Save All";
            this.templateConfigurationSaveAllButton.TextAlignment = Terminal.Gui.TextAlignment.Centered;
            this.templateConfigurationSaveAllButton.IsDefault = false;
            this.Add(this.templateConfigurationSaveAllButton);
        }
    }
}
